CREATE TABLE extended_orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    order_number VARCHAR2(255) NOT NULL,
    total_amount NUMBER(10, 2) DEFAULT 0.00 NOT NULL,
    status VARCHAR2(50) DEFAULT 'pending' NOT NULL,
    priority VARCHAR2(50) DEFAULT 'medium' NOT NULL,
    region VARCHAR2(50) DEFAULT 'default' NOT NULL,
    category VARCHAR2(255),
    product VARCHAR2(255),
    department VARCHAR2(255),
    year VARCHAR2(10),
    quarter VARCHAR2(10),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_extended_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
