CREATE TABLE extended_order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_name VARCHAR2(255) NOT NULL,
    quantity NUMBER DEFAULT 1 NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    category VARCHAR2(255),
    region VARCHAR2(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_extended_items_order FOREIGN KEY (order_id) REFERENCES extended_orders(id) ON DELETE CASCADE
)
