CREATE TABLE json_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    age NUMBER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    settings CLOB CHECK (settings IS JSON),
    tags CLOB CHECK (tags IS JSON),
    profile CLOB CHECK (profile IS JSON),
    roles CLOB CHECK (roles IS JSON),
    scores CLOB CHECK (scores IS JSON),
    subscription CLOB CHECK (subscription IS JSON),
    preferences CLOB CHECK (preferences IS JSON)
)
