CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    order_number VARCHAR2(255) NOT NULL,
    total_amount NUMBER(10, 2) DEFAULT 0.00 NOT NULL,
    status VARCHAR2(50) DEFAULT 'pending' NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id)
)
