CREATE TABLE posts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    author NUMBER,
    title VARCHAR2(255) NOT NULL,
    content CLOB,
    status VARCHAR2(50) DEFAULT 'published' NOT NULL,
    published NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    published_time TIMESTAMP,
    CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
