CREATE TABLE profiles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    bio CLOB,
    avatar_url VARCHAR2(512),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_profiles_user_id FOREIGN KEY (user_id) REFERENCES users(id)
)
