# src/rhosocial/activerecord/backend/impl/oracle/protocols/hierarchical.py
"""Protocol for hierarchical queries (CONNECT BY)."""

from typing import Protocol, runtime_checkable, Tuple, List, Any


@runtime_checkable
class HierarchicalQuerySupport(Protocol):
    def supports_hierarchical_queries(self) -> bool: ...
    def supports_connect_by(self) -> bool: ...
    def supports_level_pseudo_column(self) -> bool: ...
    def supports_connect_by_root(self) -> bool: ...
    def supports_sys_connect_by_path(self) -> bool: ...
    def format_connect_by(self, expr) -> Tuple[str, List[Any]]: ...