# src/rhosocial/activerecord/backend/impl/oracle/protocols/hint.py
"""Protocol for query hints support."""

from typing import Protocol, runtime_checkable, Tuple, List, Any


@runtime_checkable
class QueryHintSupport(Protocol):
    def supports_query_hints(self) -> bool: ...
    def supports_parallel_hint(self) -> bool: ...
    def supports_index_hint(self) -> bool: ...
    def supports_leading_hint(self) -> bool: ...
    def supports_optimizer_hints(self) -> bool: ...
    def format_hint(self, expr) -> Tuple[str, List[Any]]: ...