# src/rhosocial/activerecord/backend/impl/oracle/protocols/identifier_capabilities.py
"""Capability protocol declarations for Oracle identifier rendering.

Functional-group principle: every public format_*/supports_* on a
backend mixin is declared here so dialect users can program against
the capability contract.

Hand-maintained.  The header used to claim these were generated by
scripts/p7_generate_protocols.py, which does not exist in this repository,
so "regenerate" was not an option a reader could act on -- and a stale
signature would have gone unnoticed.  When a mixin gains a public rendering
method, add it here and keep the signature identical to the mixin's.
"""

from typing import Any, Dict, List, Optional, Tuple

from rhosocial.activerecord.backend.expression.bases import BaseExpression
from rhosocial.activerecord.backend.expression.core import Column

from typing import Protocol

class OracleIdentifierSupport(Protocol):
    """Auto-generated capability protocol (P7)."""

    def format_identifier(self, identifier: str, need_quote: bool = True) -> str:
        ...  # pragma: no cover
    def format_column(self, expr: 'Column') -> Tuple[str, Tuple]:
        ...  # pragma: no cover
    def format_table(self, expr: 'BaseExpression') -> Tuple[str, tuple]:
        ...  # pragma: no cover
