# src/rhosocial/activerecord/backend/impl/oracle/protocols/locking.py
"""Protocol for Oracle-enhanced locking features."""

from typing import Protocol, runtime_checkable, Tuple, List, Any


@runtime_checkable
class OracleLockingSupport(Protocol):
    def supports_for_update_nowait(self) -> bool: ...
    def supports_for_update_wait(self) -> bool: ...
    def supports_for_update_of(self) -> bool: ...
    def format_for_update(self, expr) -> Tuple[str, List[Any]]: ...