# src/rhosocial/activerecord/backend/impl/oracle/protocols/pivot.py
"""Protocol for PIVOT/UNPIVOT operations."""

from typing import Protocol, runtime_checkable, Tuple, List, Any


@runtime_checkable
class PivotSupport(Protocol):
    def supports_pivot(self) -> bool: ...
    def supports_unpivot(self) -> bool: ...
    def supports_pivot_xml(self) -> bool: ...
    def format_pivot(self, expr) -> Tuple[str, List[Any]]: ...
    def format_unpivot(self, expr) -> Tuple[str, List[Any]]: ...