-- Oracle version of the column_mapping_items table schema

CREATE TABLE column_mapping_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    item_total NUMBER NOT NULL,
    remarks NUMBER
)
