-- Oracle version of the comments table schema

CREATE TABLE comments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_ref NUMBER NOT NULL,
    author NUMBER NOT NULL,
    text CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    approved NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_comments_post FOREIGN KEY (postRef) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_author FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_comments_post_ref ON comments(postRef);
CREATE INDEX idx_comments_author ON comments(author);
