-- Oracle version of the mixed_annotation_items table schema

CREATE TABLE mixed_annotation_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    tags VARCHAR2(4000),
    meta VARCHAR2(4000),
    description VARCHAR2(4000),
    status VARCHAR2(4000)
)
