-- Oracle version of the posts table schema

CREATE TABLE posts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    content CLOB,
    published_at TIMESTAMP,
    published NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_posts_author FOREIGN KEY (author) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_posts_author ON posts(author);
