CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    price NUMBER(10,2),
    quantity NUMBER(10),
    description CLOB,
    product_code VARCHAR2(100),
    category VARCHAR2(255)
)