-- Oracle version of the pydantic_validated_models table schema

CREATE TABLE pydantic_validated_models (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(32),
    quantity NUMBER,
    step_count NUMBER,
    price NUMBER(10, 2),
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    status VARCHAR2(32),
    normalized_name VARCHAR2(50),
    created_token VARCHAR2(255)
)
