-- Oracle version of the type_adapter_tests table schema

CREATE TABLE type_adapter_tests (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    optional_name VARCHAR2(255),
    optional_age NUMBER,
    last_login VARCHAR2(4000),
    is_premium NUMBER(1),
    unsupported_union VARCHAR2(255),
    custom_bool VARCHAR2(3),
    optional_custom_bool VARCHAR2(3)
)
