-- Oracle version of the validated_field_users table schema

CREATE TABLE validated_field_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    age NUMBER,
    balance NUMBER(10,2),
    credit_score NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'active' NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT chk_status CHECK (status IN ('active', 'inactive', 'banned', 'pending', 'suspended'))
)
