-- Oracle version of the validated_users table schema

CREATE TABLE validated_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    age NUMBER
)
