"""
Oracle JSON Functions — JSON_VALUE, JSON_QUERY, JSON_EXISTS, JSON_OBJECT, JSON_ARRAY.

Oracle 12c+ supports JSON operations natively. 21c+ adds a native JSON data type.

This example demonstrates:
1. JSON_VALUE — extract a scalar value
2. JSON_QUERY — extract a JSON object/array
3. JSON_EXISTS — check if a JSON path exists
4. JSON_OBJECT — construct a JSON object
5. JSON_ARRAY — construct a JSON array
6. JSON_TABLE — query JSON as a relational table
7. IS JSON constraint

Oracle Version Support: 12c+ (JSON_TABLE 12.1.0.2+, native JSON datatype 21c+)
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE json_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        payload CLOB CHECK (payload IS JSON)
    )
""", options=DDL)

backend.execute(
    "INSERT INTO json_demo (name, payload) VALUES (:1, :2)",
    ("Product A", '{"price": 19.99, "tags": ["sale", "new"], "stock": {"qty": 100, "loc": "A1"}}'),
    options=ExecutionOptions(stmt_type=StatementType.INSERT),
)
backend.execute(
    "INSERT INTO json_demo (name, payload) VALUES (:1, :2)",
    ("Product B", '{"price": 29.99, "tags": ["premium"], "stock": {"qty": 50, "loc": "B2"}}'),
    options=ExecutionOptions(stmt_type=StatementType.INSERT),
)

print("=" * 60)
print("Oracle JSON Function Examples")
print("=" * 60)

print("\n[1] JSON_VALUE — extract scalar")
result = backend.execute(
    "SELECT name, JSON_VALUE(payload, '$.stock.qty' RETURNING NUMBER) AS qty "
    "FROM json_demo ORDER BY id",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}: stock qty = {row['qty']}")

print("\n[2] JSON_QUERY — extract object/array")
result = backend.execute(
    "SELECT name, JSON_QUERY(payload, '$.tags') AS tags FROM json_demo ORDER BY id",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}: tags = {row['tags']}")

print("\n[3] JSON_EXISTS — path existence check (in WHERE clause)")
result = backend.execute(
    "SELECT name FROM json_demo WHERE JSON_EXISTS(payload, '$.stock.loc') ORDER BY id",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']} has stock.loc")

print("\n[4] JSON_OBJECT — construct JSON")
result = backend.execute(
    "SELECT JSON_OBJECT('product' VALUE name, 'qty' VALUE JSON_VALUE(payload, '$.stock.qty')) "
    "AS obj FROM json_demo ORDER BY id",
    options=DQL,
)
for row in result.data:
    print(f"  {row['obj']}")

print("\n[5] JSON_ARRAY — construct JSON array")
result = backend.execute(
    "SELECT JSON_ARRAY(name, JSON_VALUE(payload, '$.price' RETURNING NUMBER)) "
    "AS arr FROM json_demo ORDER BY id",
    options=DQL,
)
for row in result.data:
    print(f"  {row['arr']}")

print("\n[6] JSON_TABLE — query JSON as relational table")
try:
    result = backend.execute(
        "SELECT jt.tag_name FROM json_demo, "
        "JSON_TABLE(json_demo.payload, '$.tags[*]' COLUMNS (tag_name VARCHAR2(50) PATH '$')) jt "
        "WHERE json_demo.id = 1",
        options=DQL,
    )
    for row in result.data:
        print(f"  tag: {row['tag_name']}")
except Exception as e:
    print(f"  JSON_TABLE requires Oracle 12.1.0.2+. Error: {e}")

backend.execute("DROP TABLE json_demo PURGE", options=DDL)
backend.disconnect()
print("\nJSON function examples completed successfully.")