# src/rhosocial/activerecord/backend/impl/oracle/expression/ddl/__init__.py
"""Oracle DDL expression sub-package.

Hosts Oracle-specific DDL expressions that do not map onto a core statement
class, e.g. synonyms and database links.
"""

from .database_link import (
    OracleCreateDatabaseLinkExpression,
    OracleDropDatabaseLinkExpression,
)
from .routine import (
    OracleCreateFunctionExpression,
    OracleCreatePackageBodyExpression,
    OracleCreatePackageExpression,
    OracleCreateProcedureExpression,
    OracleDropRoutineExpression,
    OracleDropRoutineObjectType,
    OracleRoutineParameter,
    OracleRoutineParameterMode,
)
from .synonym import (
    OracleCreateSynonymExpression,
    OracleDropSynonymExpression,
)
from .type import (
    DropTypeBodyExpression,
    OracleAlterTypeAddAttributeAction,
    OracleAlterTypeAddMethodAction,
    OracleAlterTypeCompileAction,
    OracleAlterTypeDependentHandling,
    OracleTypeDependentHandling,
    OracleAlterTypeAttributeAction,
    OracleAlterTypeMethodAction,
    OracleAlterTypeModifyLimitAction,
    OracleCompileTypeAction,
    OracleSetTypeFinalAction,
    OracleSetTypeInstantiableAction,
    OracleAlterTypeDropAttributeAction,
    OracleAlterTypeDropMethodAction,
    OracleAlterTypeElementTypeAction,
    OracleAlterTypeFinalAction,
    OracleAlterTypeInstantiableAction,
    OracleAlterTypeLimitAction,
    OracleAlterTypeModifyAttributeAction,
    OracleAlterTypeResetAction,
    OracleCreateTypeBodyExpression,
    OracleDropTypeBodyExpression,
    OracleDropTypeExpression,
    OracleIncompleteTypeDefinition,
    OracleNestedTableTypeDefinition,
    OracleObjectTypeDefinition,
    OracleSqljTypeDefinition,
    OracleTypeAlterAction,
    OracleTypeAttribute,
    OracleTypeMethod,
    OracleVarrayTypeDefinition,
)

__all__ = [
    "OracleCreateSynonymExpression",
    "OracleDropSynonymExpression",
    "OracleCreateDatabaseLinkExpression",
    "OracleDropDatabaseLinkExpression",
    "OracleRoutineParameterMode",
    "OracleRoutineParameter",
    "OracleCreateProcedureExpression",
    "OracleCreateFunctionExpression",
    "OracleCreatePackageExpression",
    "OracleCreatePackageBodyExpression",
    "OracleDropRoutineObjectType",
    "OracleDropRoutineExpression",
    "OracleTypeAttribute",
    "OracleTypeMethod",
    "OracleObjectTypeDefinition",
    "OracleSqljTypeDefinition",
    "OracleVarrayTypeDefinition",
    "OracleNestedTableTypeDefinition",
    "OracleIncompleteTypeDefinition",
    "OracleAlterTypeDependentHandling",
    "OracleTypeDependentHandling",
    "OracleAlterTypeAttributeAction",
    "OracleAlterTypeMethodAction",
    "OracleAlterTypeModifyLimitAction",
    "OracleCompileTypeAction",
    "OracleSetTypeFinalAction",
    "OracleSetTypeInstantiableAction",
    "OracleTypeAlterAction",
    "OracleAlterTypeAddAttributeAction",
    "OracleAlterTypeModifyAttributeAction",
    "OracleAlterTypeDropAttributeAction",
    "OracleAlterTypeAddMethodAction",
    "OracleAlterTypeDropMethodAction",
    "OracleAlterTypeLimitAction",
    "OracleAlterTypeElementTypeAction",
    "OracleAlterTypeCompileAction",
    "OracleAlterTypeFinalAction",
    "OracleAlterTypeInstantiableAction",
    "OracleAlterTypeResetAction",
    "OracleCreateTypeBodyExpression",
    "OracleDropTypeExpression",
    "DropTypeBodyExpression",
    "OracleDropTypeBodyExpression",
]
