-- tests/rhosocial/activerecord_oracle_test/feature/mixins/schema/combined_articles.sql
CREATE TABLE combined_articles (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    content CLOB NOT NULL,
    status VARCHAR2(50) DEFAULT 'draft' NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    version NUMBER(10) DEFAULT 1 NOT NULL,
    deleted_at TIMESTAMP NULL
)
