-- tests/rhosocial/activerecord_oracle_test/feature/mixins/schema/tasks.sql
CREATE TABLE tasks (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    is_completed NUMBER(1) DEFAULT 0 NOT NULL,
    deleted_at TIMESTAMP NULL
)
