-- tests/rhosocial/activerecord_oracle_test/feature/mixins/schema/timestamped_posts.sql
CREATE TABLE timestamped_posts (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
