-- tests/rhosocial/activerecord_oracle_test/feature/mixins/schema/versioned_products.sql
CREATE TABLE versioned_products (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    price NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    version NUMBER(10) DEFAULT 1 NOT NULL
)
