"""
UPDATE Statements.

This example demonstrates:
1. Simple UPDATE with placeholder-style parameters (:1, :2, ...)
2. UPDATE with WHERE clause
3. Conditional UPDATE

Oracle Version Support: 12c+
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE update_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        score NUMBER(3) DEFAULT 0,
        status VARCHAR2(20) DEFAULT 'pending'
    )
""", options=DDL)

for n, s, st in [("Alice", 70, "active"), ("Bob", 55, "inactive"), ("Charlie", 60, "active")]:
    backend.execute(
        "INSERT INTO update_demo (name, score, status) VALUES (:1, :2, :3)",
        (n, s, st),
        options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )

print("=" * 60)
print("UPDATE Examples")
print("=" * 60)

print("\nBefore UPDATE:")
for row in backend.execute("SELECT * FROM update_demo ORDER BY id", options=DQL).data:
    print(f"  {row['id']}: {row['name']} score={row['score']} status={row['status']}")

# --- 1. Single-row UPDATE ---
print("\n[1] Single-row UPDATE")
backend.execute(
    "UPDATE update_demo SET score = :1 WHERE name = :2",
    (100, "Alice"),
    options=ExecutionOptions(stmt_type=StatementType.UPDATE),
)
print("  Alice's score updated to 100")

# --- 2. Multi-column UPDATE ---
print("\n[2] Multi-column UPDATE")
backend.execute(
    "UPDATE update_demo SET score = :1, status = :2 WHERE name = :3",
    (88, "active", "Bob"),
    options=ExecutionOptions(stmt_type=StatementType.UPDATE),
)
print("  Bob's score=88, status='active'")

# --- 3. Bulk UPDATE ---
print("\n[3] Bulk UPDATE (all pending -> active)")
backend.execute(
    "UPDATE update_demo SET status = :1 WHERE status = :2",
    ("active", "pending"),
    options=ExecutionOptions(stmt_type=StatementType.UPDATE),
)

print("\nAfter UPDATE:")
for row in backend.execute("SELECT * FROM update_demo ORDER BY id", options=DQL).data:
    print(f"  {row['id']}: {row['name']} score={row['score']} status={row['status']}")

backend.execute("DROP TABLE update_demo PURGE", options=DDL)
backend.disconnect()
print("\nUpdate examples completed successfully.")