# src/rhosocial/activerecord/backend/impl/oracle/examples/named_migrations/expressions.py
"""
DDL named expression functions for Oracle migration examples.

Each function receives a *dialect* and returns a DDL expression object.
These are the building blocks used by NamedMigration up()/down() methods.

Oracle notes
------------
Oracle has no MySQL-style ``AUTO_INCREMENT``. Instead the dialect renders
``GENERATED BY DEFAULT AS IDENTITY`` when a ``PRIMARY_KEY`` column constraint
is declared with ``is_auto_increment=True``. The expressions below follow
that convention.

Type usage follows issue #108: each column is given a concrete
``DataType`` instance rather than a free-form ``data_type`` string.
"""

from rhosocial.activerecord.backend.expression.statements.ddl_table import (
    CreateTableExpression,
    ColumnDefinition,
    ColumnConstraint,
    ColumnConstraintType,
    DropTableExpression,
)
from rhosocial.activerecord.backend.impl.oracle.expression.types import (
    OracleIntegerType,
    OracleVarChar2Type,
)


def create_users_table(dialect):
    """CREATE TABLE users (id INTEGER PRIMARY KEY IDENTITY, name VARCHAR2(255), email VARCHAR2(255))."""
    return CreateTableExpression(
        dialect,
        table="users",
        columns=[
            ColumnDefinition(
                dialect,
                "id",
                OracleIntegerType(dialect),
                constraints=[
                    ColumnConstraint(
                        dialect,
                        ColumnConstraintType.PRIMARY_KEY,
                        is_auto_increment=True,
                    ),
                ],
            ),
            ColumnDefinition(dialect, "name", OracleVarChar2Type(length=255, dialect=dialect)),
            ColumnDefinition(dialect, "email", OracleVarChar2Type(length=255, dialect=dialect)),
        ],
    )


def drop_users_table(dialect):
    """DROP TABLE IF EXISTS users."""
    return DropTableExpression(dialect, table="users", if_exists=True)


def create_posts_table(dialect):
    """CREATE TABLE posts (id INTEGER PRIMARY KEY IDENTITY, title VARCHAR2(255), user_id INTEGER)."""
    return CreateTableExpression(
        dialect,
        table="posts",
        columns=[
            ColumnDefinition(
                dialect,
                "id",
                OracleIntegerType(dialect),
                constraints=[
                    ColumnConstraint(
                        dialect,
                        ColumnConstraintType.PRIMARY_KEY,
                        is_auto_increment=True,
                    ),
                ],
            ),
            ColumnDefinition(dialect, "title", OracleVarChar2Type(length=255, dialect=dialect)),
            ColumnDefinition(dialect, "user_id", OracleIntegerType(dialect)),
        ],
    )


def drop_posts_table(dialect):
    """DROP TABLE IF EXISTS posts."""
    return DropTableExpression(dialect, table="posts", if_exists=True)


def create_custom_table(dialect, table_name: str = "custom_table"):
    """CREATE TABLE <table_name> (id INTEGER PRIMARY KEY IDENTITY, value VARCHAR2(255)).

    This expression accepts an extra ``table_name`` parameter, allowing
    the migration to control the target table name at runtime.
    """
    return CreateTableExpression(
        dialect,
        table=table_name,
        columns=[
            ColumnDefinition(
                dialect,
                "id",
                OracleIntegerType(dialect),
                constraints=[
                    ColumnConstraint(
                        dialect,
                        ColumnConstraintType.PRIMARY_KEY,
                        is_auto_increment=True,
                    ),
                ],
            ),
            ColumnDefinition(dialect, "value", OracleVarChar2Type(length=255, dialect=dialect)),
        ],
    )


def drop_custom_table(dialect, table_name: str = "custom_table"):
    """DROP TABLE IF EXISTS <table_name>."""
    return DropTableExpression(dialect, table=table_name, if_exists=True)
