# src/rhosocial/activerecord/backend/impl/oracle/protocols.py
"""
Oracle-specific protocol definitions.

These protocols define interfaces for Oracle-specific features
that can be used for type checking and capability detection.
"""

from typing import Protocol, runtime_checkable, Tuple, List, Any


@runtime_checkable
class HierarchicalQuerySupport(Protocol):
    """Protocol for databases supporting hierarchical queries (CONNECT BY)."""

    def supports_hierarchical_queries(self) -> bool: ...
    def supports_connect_by(self) -> bool: ...
    def supports_level_pseudo_column(self) -> bool: ...
    def supports_connect_by_root(self) -> bool: ...
    def supports_sys_connect_by_path(self) -> bool: ...
    def format_connect_by(self, expr) -> Tuple[str, List[Any]]: ...


@runtime_checkable
class PivotSupport(Protocol):
    """Protocol for databases supporting PIVOT/UNPIVOT operations."""

    def supports_pivot(self) -> bool: ...
    def supports_unpivot(self) -> bool: ...
    def supports_pivot_xml(self) -> bool: ...
    def format_pivot(self, expr) -> Tuple[str, List[Any]]: ...
    def format_unpivot(self, expr) -> Tuple[str, List[Any]]: ...


@runtime_checkable
class QueryHintSupport(Protocol):
    """Protocol for databases supporting query hints."""

    def supports_query_hints(self) -> bool: ...
    def supports_parallel_hint(self) -> bool: ...
    def supports_index_hint(self) -> bool: ...
    def supports_leading_hint(self) -> bool: ...
    def supports_optimizer_hints(self) -> bool: ...
    def format_hint(self, expr) -> Tuple[str, List[Any]]: ...


@runtime_checkable
class OracleLockingSupport(Protocol):
    """Protocol for Oracle-enhanced locking features."""

    def supports_for_update_nowait(self) -> bool: ...
    def supports_for_update_wait(self) -> bool: ...
    def supports_for_update_of(self) -> bool: ...
    def format_for_update(self, expr) -> Tuple[str, List[Any]]: ...


@runtime_checkable
class OracleNativeJSONSupport(Protocol):
    """Protocol for Oracle native JSON type (21c+)."""

    def supports_native_json(self) -> bool: ...


@runtime_checkable
class OracleBooleanTypeSupport(Protocol):
    """Protocol for Oracle native BOOLEAN type (23ai+)."""

    def supports_boolean_type(self) -> bool: ...


@runtime_checkable
class OracleVectorTypeSupport(Protocol):
    """Protocol for Oracle VECTOR type (23ai+)."""

    def supports_vector_type(self) -> bool: ...


@runtime_checkable
class OracleJSONDualitySupport(Protocol):
    """Protocol for Oracle JSON Relational Duality (23ai+)."""

    def supports_json_duality(self) -> bool: ...
