"""
Transaction Context Manager.

This example demonstrates:
1. backend.transaction() context manager (commit/rollback)
2. Explicit ROLLBACK on error
3. Implicit COMMIT on success
4. Nested savepoints and transaction state visibility

Oracle version: 12c+
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE txn_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        balance NUMBER(10, 2) DEFAULT 0.00
    )
""", options=DDL)

print("=" * 60)
print("Transaction Context Manager Examples")
print("=" * 60)

# --- 1. Successful transaction (commit) ---
print("\n[1] Successful transaction — auto-commit")
with backend.transaction():
    backend.execute(
        "INSERT INTO txn_demo (name, balance) VALUES (:1, :2)",
        ("Alice", 1000.00),
        options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )
    backend.execute(
        "INSERT INTO txn_demo (name, balance) VALUES (:1, :2)",
        ("Bob", 500.00),
        options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )
print("  Committed Alice and Bob")

# --- 2. Rollback on exception ---
print("\n[2] Rollback on exception (duplicate PK)")
backend.execute("CREATE TABLE txn_rollback (name VARCHAR2(5) PRIMARY KEY)", options=DDL)
try:
    with backend.transaction():
        backend.execute(
            "INSERT INTO txn_rollback (name) VALUES (:1)", ("Item1",),
            options=ExecutionOptions(stmt_type=StatementType.INSERT),
        )
        backend.execute(
            "INSERT INTO txn_rollback (name) VALUES (:1)", ("Item2_Too_Long_For_VARCHAR2_5",),
            options=ExecutionOptions(stmt_type=StatementType.INSERT),
        )
except Exception as e:
    print(f"  Exception caught: {e}")

result = backend.execute("SELECT name FROM txn_rollback", options=DQL)
print(f"  Rows after rollback: {len(result.data)} (expected 0)")
backend.execute("DROP TABLE txn_rollback PURGE", options=DDL)

# --- 3. Read within transaction ---
print("\n[3] Read visibility within transaction")
initial_count = len(backend.execute("SELECT * FROM txn_demo", options=DQL).data)
print(f"  Initial row count: {initial_count}")
with backend.transaction():
    backend.execute(
        "INSERT INTO txn_demo (name, balance) VALUES (:1, :2)",
        ("Charlie", 300.00),
        options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )
    mid_count = len(backend.execute("SELECT * FROM txn_demo", options=DQL).data)
    print(f"  During transaction: {mid_count} rows (Charlie visible)")
print(f"  After commit: {len(backend.execute('SELECT * FROM txn_demo', options=DQL).data)} rows")

backend.execute("DROP TABLE txn_demo PURGE", options=DDL)
backend.disconnect()
print("\nTransaction examples completed successfully.")