# tests/rhosocial/activerecord_oracle_test/feature/backend/test_schema_qualified_dml.py
"""Standalone schema-qualified DML round-trip (no testsuite dependency).

Mirrors the provider fixtures used by the cross_schema suite: two user
schemas (AR_CRM / AR_SHOP) host ``customers`` and ``orders``; models bind
via ``__schema_name__`` and the tests assert INSERT/UPDATE/DELETE land in
and only in the owning namespace.
"""
import pytest

from typing import ClassVar, Optional

from rhosocial.activerecord.base.field_proxy import FieldProxy
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType
from typing import Optional

from rhosocial.activerecord.model import ActiveRecord
from rhosocial.activerecord.backend.errors import DatabaseError
from providers.scenarios import get_scenario_raw

# Pin every test in this module to one xdist worker: the shared AR_*
# schemas must not be dropped while another worker is mid-test.
pytestmark = pytest.mark.xdist_group("oracle_schema_dml")

SCHEMA_USERS = ("AR_CRM", "AR_SHOP")
SCHEMA_USER_PASSWORD = "Rh0social#2026"


class SchemaCustomer(ActiveRecord):
    __table_name__ = "customers"
    __schema_name__ = "ar_crm"
    __primary_key__ = "id"
    c: ClassVar[FieldProxy] = FieldProxy()

    id: Optional[int] = None
    name: str


class SchemaOrder(ActiveRecord):
    __table_name__ = "orders"
    __schema_name__ = "ar_shop"
    __primary_key__ = "id"
    c: ClassVar[FieldProxy] = FieldProxy()

    id: Optional[int] = None
    customer_id: int
    amount: int


def _ddl_options():
    return ExecutionOptions(stmt_type=StatementType.DDL)


def _drop_user_block(user: str) -> str:
    return (
        f"BEGIN EXECUTE IMMEDIATE 'DROP USER {user} CASCADE'; "
        f"EXCEPTION WHEN OTHERS THEN NULL; END;"
    )


import time as _time


def _create_user_with_retry(backend, user: str, attempts: int = 3) -> None:
    """CREATE USER right after DROP USER CASCADE can race on older images
    (ORA-01920/01918); re-run the drop and retry."""
    for attempt in range(attempts):
        try:
            backend.execute(
                f'CREATE USER {user} IDENTIFIED BY "{SCHEMA_USER_PASSWORD}"',
                options=_ddl_options(),
            )
            return
        except DatabaseError as exc:
            if "ORA-01920" not in str(exc) or attempt == attempts - 1:
                raise
            backend.execute(_drop_user_block(user), options=_ddl_options())
            _time.sleep(1.5)


def _provision(backend) -> None:
    for user in SCHEMA_USERS:
        backend.execute(_drop_user_block(user), options=_ddl_options())
    for user in SCHEMA_USERS:
        _create_user_with_retry(backend, user)
        backend.execute(f"GRANT UNLIMITED TABLESPACE TO {user}", options=_ddl_options())
    statements = [
        (
            "CREATE TABLE AR_CRM.CUSTOMERS ("
            "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(100) NOT NULL)"
        ),
        (
            "CREATE TABLE AR_SHOP.ORDERS ("
            "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
            "customer_id NUMBER NOT NULL, amount NUMBER NOT NULL)"
        ),
    ]
    for sql in statements:
        backend.execute(sql, options=_ddl_options())


def _cleanup(backend) -> None:
    for user in SCHEMA_USERS:
        try:
            backend.execute(_drop_user_block(user), options=_ddl_options())
        except Exception:
            pass


@pytest.fixture(scope="module")
def provisioned():
    backend_class, config = get_scenario_raw("oracle_23c")
    SchemaCustomer.configure(config, backend_class)
    backend = SchemaCustomer.__backend__
    if not backend._connection:
        backend.connect()
    try:
        _provision(backend)
    except DatabaseError as exc:
        if "ORA-01031" in str(exc):
            pytest.skip("connected user lacks privileges to create schema users")
        raise

    SchemaOrder.__connection_config__ = config
    SchemaOrder.__backend_class__ = backend_class
    SchemaOrder.__backend__ = backend
    yield
    _cleanup(backend)


def test_insert_lands_in_own_namespace(provisioned):
    cust = SchemaCustomer(name="dml_alice")
    cust.save()
    order = SchemaOrder(customer_id=cust.id, amount=42)
    order.save()

    assert SchemaCustomer.query().where(SchemaCustomer.c.name == "dml_alice").count() == 1
    assert SchemaOrder.query().where(SchemaOrder.c.amount == 42).count() == 1


def test_update_and_delete_are_scoped(provisioned):
    cust = SchemaCustomer(name="dml_bob")
    cust.save()
    order = SchemaOrder(customer_id=cust.id, amount=10)
    order.save()

    SchemaOrder.query().where(SchemaOrder.c.id == order.id).update_all({"amount": 11})
    refreshed = SchemaOrder.query().where(SchemaOrder.c.id == order.id).one()
    assert refreshed.amount == 11

    SchemaOrder.query().where(SchemaOrder.c.id == order.id).delete_all()
    assert SchemaOrder.query().where(SchemaOrder.c.id == order.id).count() == 0
    # The customer row is untouched by order-scoped deletes.
    assert SchemaCustomer.query().where(SchemaCustomer.c.id == cust.id).count() == 1


@pytest.mark.asyncio
async def test_async_insert_is_scoped(provisioned):
    from typing import Optional as _Optional

    from rhosocial.activerecord.backend.impl.oracle import AsyncOracleBackend
    from rhosocial.activerecord.model import AsyncActiveRecord

    class AsyncSchemaCustomer(AsyncActiveRecord):
        __table_name__ = "customers"
        __schema_name__ = "ar_crm"
        __primary_key__ = "id"
        c: ClassVar[FieldProxy] = FieldProxy()

        id: _Optional[int] = None
        name: str

    _, config = get_scenario_raw("oracle_23c")
    backend = AsyncOracleBackend(connection_config=config)
    await backend.connect()
    try:
        AsyncSchemaCustomer.__connection_config__ = config
        AsyncSchemaCustomer.__backend_class__ = AsyncOracleBackend
        AsyncSchemaCustomer.__backend__ = backend

        cust = AsyncSchemaCustomer(name="dml_async")
        await cust.save()
        assert (
            await AsyncSchemaCustomer.query()
            .where(AsyncSchemaCustomer.c.name == "dml_async")
            .count()
            == 1
        )

        await AsyncSchemaCustomer.query().where(
            AsyncSchemaCustomer.c.name == "dml_async"
        ).delete_all()
        assert (
            await AsyncSchemaCustomer.query()
            .where(AsyncSchemaCustomer.c.name == "dml_async")
            .count()
            == 0
        )
    finally:
        try:
            await backend.disconnect()
        except Exception:
            pass
