# tests/rhosocial/activerecord_oracle_test/feature/backend/dml/test_dml_deep_async.py
"""Async backend DML depth: execute_many batches, transaction boundaries,
and the asynchronous RETURNING INTO insert path.

Provisions AR_CRM/AR_SHOP like test_schema_qualified_dml; pinned to the
``oracle_schema_dml`` xdist group so the shared schemas are never dropped
under a concurrent worker.
"""
from typing import ClassVar, List, Optional, Tuple

import pytest

from rhosocial.activerecord.base.field_proxy import FieldProxy
from rhosocial.activerecord.backend.errors import DatabaseError
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType
from rhosocial.activerecord.model import AsyncActiveRecord
from providers.scenarios import get_scenario_raw

pytestmark = pytest.mark.xdist_group("oracle_schema_dml")

SCHEMA_USERS = ("AR_CRM", "AR_SHOP")
SCHEMA_USER_PASSWORD = "Rh0social#2026"

BATCH_TABLE = "AR_CRM.ASYNC_BATCH"


class AsyncCustomer(AsyncActiveRecord):
    __table_name__ = "customers"
    __schema_name__ = "ar_crm"
    __primary_key__ = "id"
    c: ClassVar[FieldProxy] = FieldProxy()

    id: Optional[int] = None
    name: str


def _ddl_options() -> ExecutionOptions:
    return ExecutionOptions(stmt_type=StatementType.DDL)


def _select_options() -> ExecutionOptions:
    return ExecutionOptions(stmt_type=StatementType.SELECT)


def _drop_user_block(user: str) -> str:
    return (f"BEGIN EXECUTE IMMEDIATE 'DROP USER {user} CASCADE'; "
            f"EXCEPTION WHEN OTHERS THEN NULL; END;")


@pytest.fixture(scope="module")
def provisioned():
    from rhosocial.activerecord.backend.impl.oracle import OracleBackend

    backend_class, config = get_scenario_raw("oracle_23c")
    backend = OracleBackend(connection_config=config)
    backend.connect()
    try:
        for user in SCHEMA_USERS:
            backend.execute(_drop_user_block(user), options=_ddl_options())
        for user in SCHEMA_USERS:
            try:
                backend.execute(
                    f'CREATE USER {user} IDENTIFIED BY "{SCHEMA_USER_PASSWORD}"',
                    options=_ddl_options(),
                )
            except DatabaseError as exc:
                if "ORA-01031" in str(exc):
                    pytest.skip(
                        "connected user lacks privileges to create schema users"
                    )
                raise
            backend.execute(f"GRANT UNLIMITED TABLESPACE TO {user}",
                            options=_ddl_options())
        statements = [
            "CREATE TABLE AR_CRM.CUSTOMERS (id NUMBER GENERATED BY DEFAULT "
            "AS IDENTITY PRIMARY KEY, name VARCHAR2(100) NOT NULL)",
            f"CREATE TABLE {BATCH_TABLE} (name VARCHAR2(50))",
        ]
        for statement in statements:
            backend.execute(statement, options=_ddl_options())
    except Exception:
        backend.disconnect()
        raise
    yield config
    for user in SCHEMA_USERS:
        try:
            backend.execute(_drop_user_block(user), options=_ddl_options())
        except Exception:
            pass
    backend.disconnect()


@pytest.fixture
async def async_backend(provisioned):
    from rhosocial.activerecord.backend.impl.oracle import AsyncOracleBackend

    backend = AsyncOracleBackend(connection_config=provisioned)
    await backend.connect()
    yield backend
    try:
        await backend.disconnect()
    except Exception:
        pass


async def fetch_scalar(backend, sql: str) -> object:
    result = await backend.execute(sql, options=_select_options())
    rows = result.data or []
    first = rows[0]
    if isinstance(first, dict):
        return list(first.values())[0]
    return first[0]


class TestExecuteMany:
    @pytest.mark.asyncio
    async def test_batch_insert_reports_total_affected_rows(self, async_backend):
        sql = f"INSERT INTO {BATCH_TABLE} (name) VALUES (:1)"
        params_list: List[Tuple[str]] = [(f"row_{i}",) for i in range(5)]
        result = await async_backend.execute_many(sql, params_list)
        assert result.affected_rows == 5
        count = await fetch_scalar(
            async_backend, f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE}"
        )
        assert int(count) == 5

    @pytest.mark.asyncio
    async def test_empty_params_list_is_noop(self, async_backend):
        before = await fetch_scalar(
            async_backend, f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE}"
        )
        result = await async_backend.execute_many(
            f"INSERT INTO {BATCH_TABLE} (name) VALUES (:1)", []
        )
        assert result is not None
        after = await fetch_scalar(
            async_backend, f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE}"
        )
        assert before == after

    @pytest.mark.asyncio
    async def test_qmark_placeholders_are_converted_in_batch(self, async_backend):
        sql = f"INSERT INTO {BATCH_TABLE} (name) VALUES (?)"
        params_list = [(f"qmark_{i}",) for i in range(3)]
        result = await async_backend.execute_many(sql, params_list)
        assert result.affected_rows == 3
        count = await fetch_scalar(
            async_backend,
            f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE} "
            f"WHERE name LIKE 'qmark_%'",
        )
        assert int(count) == 3


class TestTransactionBoundaries:
    @pytest.mark.asyncio
    async def test_in_transaction_flag_toggles(self, async_backend):
        assert async_backend.in_transaction is False
        await async_backend.begin_transaction()
        assert async_backend.in_transaction is True
        await async_backend.rollback_transaction()
        assert async_backend.in_transaction is False

    @pytest.mark.asyncio
    async def test_rollback_discards_uncommitted_insert(self, async_backend):
        await async_backend.begin_transaction()
        try:
            await async_backend.execute(
                f"INSERT INTO {BATCH_TABLE} (name) VALUES (:1)",
                ("rollback_me",),
                options=ExecutionOptions(stmt_type=StatementType.INSERT),
            )
        finally:
            await async_backend.rollback_transaction()
        remaining = await fetch_scalar(
            async_backend,
            f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE} "
            f"WHERE name = 'rollback_me'",
        )
        assert int(remaining) == 0

    @pytest.mark.asyncio
    async def test_commit_persists_insert(self, async_backend):
        await async_backend.begin_transaction()
        try:
            await async_backend.execute(
                f"INSERT INTO {BATCH_TABLE} (name) VALUES (:1)",
                ("commit_me",),
                options=ExecutionOptions(stmt_type=StatementType.INSERT),
            )
            await async_backend.commit_transaction()
        except Exception:
            await async_backend.rollback_transaction()
            raise
        persisted = await fetch_scalar(
            async_backend,
            f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE} WHERE name = 'commit_me'",
        )
        assert int(persisted) == 1


class TestReturningIntoInsert:
    @pytest.mark.asyncio
    async def test_save_populates_identity_via_returning(
        self, async_backend, provisioned
    ):
        AsyncCustomer.__connection_config__ = provisioned
        AsyncCustomer.__backend_class__ = type(async_backend)
        AsyncCustomer.__backend__ = async_backend

        customer = AsyncCustomer(name="async_returning")
        await customer.save()
        assert isinstance(customer.id, int)
        fetched = await AsyncCustomer.query().where(
            AsyncCustomer.c.id == customer.id
        ).one()
        assert fetched.name == "async_returning"
        assert fetched.id == customer.id

        await AsyncCustomer.query().where(
            AsyncCustomer.c.id == customer.id
        ).delete_all()
        count = await AsyncCustomer.query().where(
            AsyncCustomer.c.name == "async_returning"
        ).count()
        assert count == 0

    @pytest.mark.asyncio
    async def test_identity_values_increment_across_saves(
        self, async_backend, provisioned
    ):
        AsyncCustomer.__connection_config__ = provisioned
        AsyncCustomer.__backend_class__ = type(async_backend)
        AsyncCustomer.__backend__ = async_backend

        first = AsyncCustomer(name="seq_a")
        second = AsyncCustomer(name="seq_b")
        await first.save()
        await second.save()
        assert int(second.id) > int(first.id)
        await AsyncCustomer.query().where(
            AsyncCustomer.c.id >= first.id
        ).delete_all()
