# tests/rhosocial/activerecord_oracle_test/feature/backend/dml/test_dml_deep.py
"""Sync backend DML depth: execute_many batches, transaction boundaries,
and the synchronous RETURNING INTO insert path.

Sync twin of test_dml_deep_async.py. Provisions AR_CRM/AR_SHOP like
test_schema_qualified_dml; pinned to the ``oracle_schema_dml`` xdist group so
the shared schemas are never dropped under a concurrent worker.
"""
from typing import ClassVar, List, Optional, Tuple

import pytest

from rhosocial.activerecord.base.field_proxy import FieldProxy
from rhosocial.activerecord.backend.errors import DatabaseError
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType
from rhosocial.activerecord.model import ActiveRecord
from providers.scenarios import get_scenario_raw

pytestmark = pytest.mark.xdist_group("oracle_schema_dml")

SCHEMA_USERS = ("AR_CRM", "AR_SHOP")
SCHEMA_USER_PASSWORD = "Rh0social#2026"

BATCH_TABLE = "AR_CRM.SYNC_BATCH"


class Customer(ActiveRecord):
    __table_name__ = "customers"
    __schema_name__ = "ar_crm"
    __primary_key__ = "id"
    c: ClassVar[FieldProxy] = FieldProxy()

    id: Optional[int] = None
    name: str


def _ddl_options() -> ExecutionOptions:
    return ExecutionOptions(stmt_type=StatementType.DDL)


def _select_options() -> ExecutionOptions:
    return ExecutionOptions(stmt_type=StatementType.SELECT)


def _drop_user_block(user: str) -> str:
    return (f"BEGIN EXECUTE IMMEDIATE 'DROP USER {user} CASCADE'; "
            f"EXCEPTION WHEN OTHERS THEN NULL; END;")


@pytest.fixture(scope="module")
def provisioned():
    from rhosocial.activerecord.backend.impl.oracle import OracleBackend

    backend_class, config = get_scenario_raw("oracle_23c")
    backend = OracleBackend(connection_config=config)
    backend.connect()
    try:
        for user in SCHEMA_USERS:
            backend.execute(_drop_user_block(user), options=_ddl_options())
        for user in SCHEMA_USERS:
            try:
                backend.execute(
                    f'CREATE USER {user} IDENTIFIED BY "{SCHEMA_USER_PASSWORD}"',
                    options=_ddl_options(),
                )
            except DatabaseError as exc:
                if "ORA-01031" in str(exc):
                    pytest.skip(
                        "connected user lacks privileges to create schema users"
                    )
                raise
            backend.execute(f"GRANT UNLIMITED TABLESPACE TO {user}",
                            options=_ddl_options())
        statements = [
            "CREATE TABLE AR_CRM.CUSTOMERS (id NUMBER GENERATED BY DEFAULT "
            "AS IDENTITY PRIMARY KEY, name VARCHAR2(100) NOT NULL)",
            f"CREATE TABLE {BATCH_TABLE} (name VARCHAR2(50))",
        ]
        for statement in statements:
            backend.execute(statement, options=_ddl_options())
    except Exception:
        backend.disconnect()
        raise
    yield config
    for user in SCHEMA_USERS:
        try:
            backend.execute(_drop_user_block(user), options=_ddl_options())
        except Exception:
            pass
    backend.disconnect()


@pytest.fixture
def sync_backend(provisioned):
    from rhosocial.activerecord.backend.impl.oracle import OracleBackend

    backend = OracleBackend(connection_config=provisioned)
    backend.connect()
    yield backend
    try:
        backend.disconnect()
    except Exception:
        pass


def fetch_scalar(backend, sql: str) -> object:
    result = backend.execute(sql, options=_select_options())
    rows = result.data or []
    first = rows[0]
    if isinstance(first, dict):
        return list(first.values())[0]
    return first[0]


class TestExecuteMany:
    def test_batch_insert_reports_total_affected_rows(self, sync_backend):
        """Batch INSERT should report one affected row per parameter set."""
        sql = f"INSERT INTO {BATCH_TABLE} (name) VALUES (:1)"
        params_list: List[Tuple[str]] = [(f"row_{i}",) for i in range(5)]
        result = sync_backend.execute_many(sql, params_list)
        assert result.affected_rows == 5, "batch insert should report all 5 affected rows"
        count = fetch_scalar(
            sync_backend, f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE}"
        )
        assert int(count) == 5, "all 5 batch rows should be persisted"

    def test_empty_params_list_is_noop(self, sync_backend):
        """An empty parameter list must not insert anything nor error."""
        before = fetch_scalar(
            sync_backend, f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE}"
        )
        result = sync_backend.execute_many(
            f"INSERT INTO {BATCH_TABLE} (name) VALUES (:1)", []
        )
        assert result is not None, "execute_many should return a QueryResult even for empty params"
        after = fetch_scalar(
            sync_backend, f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE}"
        )
        assert before == after, "empty batch must not change the row count"

    def test_qmark_placeholders_are_converted_in_batch(self, sync_backend):
        """``?`` placeholders are rewritten to Oracle ``:N`` inside a batch."""
        sql = f"INSERT INTO {BATCH_TABLE} (name) VALUES (?)"
        params_list = [(f"qmark_{i}",) for i in range(3)]
        result = sync_backend.execute_many(sql, params_list)
        assert result.affected_rows == 3, "qmark batch should affect 3 rows"
        count = fetch_scalar(
            sync_backend,
            f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE} "
            f"WHERE name LIKE 'qmark_%'",
        )
        assert int(count) == 3, "3 qmark rows should be persisted"


class TestTransactionBoundaries:
    def test_in_transaction_flag_toggles(self, sync_backend):
        """begin/rollback should toggle the in_transaction flag."""
        assert sync_backend.in_transaction is False, "no transaction before begin"
        sync_backend.begin_transaction()
        assert sync_backend.in_transaction is True, "in_transaction after begin"
        sync_backend.rollback_transaction()
        assert sync_backend.in_transaction is False, "no transaction after rollback"

    def test_rollback_discards_uncommitted_insert(self, sync_backend):
        """A rolled-back INSERT must leave no rows behind."""
        sync_backend.begin_transaction()
        try:
            sync_backend.execute(
                f"INSERT INTO {BATCH_TABLE} (name) VALUES (:1)",
                ("rollback_me",),
                options=ExecutionOptions(stmt_type=StatementType.INSERT),
            )
        finally:
            sync_backend.rollback_transaction()
        remaining = fetch_scalar(
            sync_backend,
            f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE} "
            f"WHERE name = 'rollback_me'",
        )
        assert int(remaining) == 0, "rolled-back insert must not persist"

    def test_commit_persists_insert(self, sync_backend):
        """A committed INSERT must be visible after the transaction ends."""
        sync_backend.begin_transaction()
        try:
            sync_backend.execute(
                f"INSERT INTO {BATCH_TABLE} (name) VALUES (:1)",
                ("commit_me",),
                options=ExecutionOptions(stmt_type=StatementType.INSERT),
            )
            sync_backend.commit_transaction()
        except Exception:
            sync_backend.rollback_transaction()
            raise
        persisted = fetch_scalar(
            sync_backend,
            f"SELECT COUNT(*) AS CNT FROM {BATCH_TABLE} WHERE name = 'commit_me'",
        )
        assert int(persisted) == 1, "committed insert must persist exactly one row"


class TestReturningIntoInsert:
    def test_save_populates_identity_via_returning(self, sync_backend, provisioned):
        """save() on an identity-keyed model must populate id via RETURNING INTO."""
        Customer.__connection_config__ = provisioned
        Customer.__backend_class__ = type(sync_backend)
        Customer.__backend__ = sync_backend

        customer = Customer(name="sync_returning")
        customer.save()
        assert isinstance(customer.id, int), "identity id should be populated by save()"
        fetched = Customer.query().where(
            Customer.c.id == customer.id
        ).one()
        assert fetched.name == "sync_returning", "fetched row should round-trip the name"
        assert fetched.id == customer.id, "fetched id should match the saved identity"

        Customer.query().where(
            Customer.c.id == customer.id
        ).delete_all()
        count = Customer.query().where(
            Customer.c.name == "sync_returning"
        ).count()
        assert count == 0, "deleted row must no longer be counted"

    def test_identity_values_increment_across_saves(self, sync_backend, provisioned):
        """Successive saves must receive increasing identity values."""
        Customer.__connection_config__ = provisioned
        Customer.__backend_class__ = type(sync_backend)
        Customer.__backend__ = sync_backend

        first = Customer(name="seq_a")
        second = Customer(name="seq_b")
        first.save()
        second.save()
        assert int(second.id) > int(first.id), "identity must increase across saves"
        Customer.query().where(
            Customer.c.id >= first.id
        ).delete_all()