-- tests/rhosocial/activerecord_oracle_test/feature/events/schema/event_tests.sql
CREATE TABLE event_tests (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) DEFAULT 'draft' NOT NULL,
    revision NUMBER(10) DEFAULT 1 NOT NULL,
    content CLOB,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
)
