-- tests/rhosocial/activerecord_oracle_test/feature/events/schema/event_tracking_models.sql
CREATE TABLE event_tracking_models (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    content CLOB NOT NULL,
    view_count NUMBER(10) DEFAULT 0 NOT NULL,
    last_viewed_at TIMESTAMP NULL
)
