# tests/rhosocial/activerecord_oracle_test/feature/backend/test_crud_async_backend.py
"""
Basic CRUD tests for Oracle async backend.
"""
import pytest
import uuid

from rhosocial.activerecord.backend.schema import StatementType
from rhosocial.activerecord.backend.options import ExecutionOptions


def unique_table_name(base: str = "test_async_crud") -> str:
    """Generate unique table name for test isolation."""
    return f"{base}_{uuid.uuid4().hex[:8]}"


class TestAsyncOracleBackendConnection:
    """Test basic Oracle async backend connection functionality."""

    @pytest.mark.asyncio
    async def test_connect(self, async_oracle_backend_single):
        """Test that backend connects successfully."""
        assert async_oracle_backend_single is not None
        assert async_oracle_backend_single._connection is not None

    @pytest.mark.asyncio
    async def test_ping(self, async_oracle_backend_single):
        """Test ping functionality."""
        result = await async_oracle_backend_single.ping(reconnect=False)
        assert result is True

    @pytest.mark.asyncio
    async def test_execute_simple_query(self, async_oracle_backend_single):
        """Test executing a simple query."""
        result = await async_oracle_backend_single.execute(
            "SELECT 1 AS value FROM DUAL",
            options=ExecutionOptions(stmt_type=StatementType.SELECT)
        )
        assert result is not None
        assert result.data is not None
        assert len(result.data) == 1
        # Column names are lowercased by the backend
        assert result.data[0]['value'] == 1

    @pytest.mark.asyncio
    async def test_get_server_version(self, async_oracle_backend_single):
        """Test getting server version."""
        version = await async_oracle_backend_single.get_server_version()
        assert version is not None
        assert isinstance(version, tuple)
        assert len(version) >= 2
        assert version[0] >= 18


class TestAsyncOracleBackendCRUD:
    """Test CRUD operations on Oracle async backend."""

    @pytest.mark.asyncio
    async def test_create_table(self, async_oracle_backend_single):
        """Test creating a table."""
        table_name = unique_table_name()

        await async_oracle_backend_single.execute(f"""
            CREATE TABLE {table_name} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL,
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP
            )
        """, options=ExecutionOptions(stmt_type=StatementType.DDL))

        result = await async_oracle_backend_single.execute(
            f"SELECT table_name FROM user_tables WHERE table_name = '{table_name.upper()}'",
            options=ExecutionOptions(stmt_type=StatementType.SELECT)
        )
        assert len(result.data) == 1

        # Cleanup
        await async_oracle_backend_single.execute(
            f"DROP TABLE {table_name} PURGE",
            options=ExecutionOptions(stmt_type=StatementType.DDL)
        )

    @pytest.mark.asyncio
    async def test_insert_and_select(self, async_oracle_backend_single):
        """Test inserting and selecting data."""
        table_name = unique_table_name()

        await async_oracle_backend_single.execute(f"""
            CREATE TABLE {table_name} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL
            )
        """, options=ExecutionOptions(stmt_type=StatementType.DDL))

        # Insert data
        await async_oracle_backend_single.execute(
            f"INSERT INTO {table_name} (name) VALUES (:1)",
            ("test_name",),
            options=ExecutionOptions(stmt_type=StatementType.INSERT)
        )

        # Select data
        result = await async_oracle_backend_single.execute(
            f"SELECT name FROM {table_name} WHERE name = :1",
            ("test_name",),
            options=ExecutionOptions(stmt_type=StatementType.SELECT)
        )
        assert len(result.data) == 1
        # Column names are lowercased by the backend
        assert result.data[0]['name'] == 'test_name'

        # Cleanup
        await async_oracle_backend_single.execute(
            f"DROP TABLE {table_name} PURGE",
            options=ExecutionOptions(stmt_type=StatementType.DDL)
        )

    @pytest.mark.asyncio
    async def test_update(self, async_oracle_backend_single):
        """Test updating data."""
        table_name = unique_table_name()

        await async_oracle_backend_single.execute(f"""
            CREATE TABLE {table_name} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL
            )
        """, options=ExecutionOptions(stmt_type=StatementType.DDL))
        await async_oracle_backend_single.execute(
            f"INSERT INTO {table_name} (name) VALUES (:1)",
            ("original",),
            options=ExecutionOptions(stmt_type=StatementType.INSERT)
        )

        # Update
        await async_oracle_backend_single.execute(
            f"UPDATE {table_name} SET name = :1 WHERE name = :2",
            ("updated", "original"),
            options=ExecutionOptions(stmt_type=StatementType.UPDATE)
        )

        # Verify
        result = await async_oracle_backend_single.execute(
            f"SELECT name FROM {table_name}",
            options=ExecutionOptions(stmt_type=StatementType.SELECT)
        )
        assert len(result.data) == 1
        # Column names are lowercased by the backend
        assert result.data[0]['name'] == 'updated'

        # Cleanup
        await async_oracle_backend_single.execute(
            f"DROP TABLE {table_name} PURGE",
            options=ExecutionOptions(stmt_type=StatementType.DDL)
        )

    @pytest.mark.asyncio
    async def test_delete(self, async_oracle_backend_single):
        """Test deleting data."""
        table_name = unique_table_name()

        await async_oracle_backend_single.execute(f"""
            CREATE TABLE {table_name} (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100) NOT NULL
            )
        """, options=ExecutionOptions(stmt_type=StatementType.DDL))
        await async_oracle_backend_single.execute(
            f"INSERT INTO {table_name} (name) VALUES (:1)",
            ("to_delete",),
            options=ExecutionOptions(stmt_type=StatementType.INSERT)
        )

        # Delete
        await async_oracle_backend_single.execute(
            f"DELETE FROM {table_name} WHERE name = :1",
            ("to_delete",),
            options=ExecutionOptions(stmt_type=StatementType.DELETE)
        )

        # Verify
        result = await async_oracle_backend_single.execute(
            f"SELECT COUNT(*) AS cnt FROM {table_name}",
            options=ExecutionOptions(stmt_type=StatementType.SELECT)
        )
        # Column names are lowercased by the backend
        assert result.data[0]['cnt'] == 0

        # Cleanup
        await async_oracle_backend_single.execute(
            f"DROP TABLE {table_name} PURGE",
            options=ExecutionOptions(stmt_type=StatementType.DDL)
        )
