# tests/rhosocial/activerecord_oracle_test/feature/backend/test_oracle_identity_conformance.py
"""Oracle identity-column conformance: declaration, renderer, and execution.

Oracle accepts the SQL-standard ``GENERATED ... AS IDENTITY`` clause from 12c
on, so it declares the identity probes and uses core's standard
``format_identity_clause`` unchanged -- there is no Oracle override, and the
point of these tests is that the declaration, the renderer, and the live server
agree with one another.

Rendering is not execution. The unit tests below pin the declaration and the
rendered bytes; the execution tests then send the rendered ``CREATE TABLE`` to
live 18c / 21c / 23c. Every live verdict runs a sentinel first -- a malformed
identity clause must come back REJECTED on the same connection -- because an
``ACCEPTED`` that has never been contrasted with a rejection is not evidence.

Known boundary, measured on all three servers and reported rather than
asserted: Oracle spells the negative cycle option ``NOCYCLE`` and refuses
core's spaced ``NO CYCLE`` (ORA-02000). ``supports_identity_cycle`` gates the
option, not the spelling, and Oracle uses core's formatter unchanged, so a
``cycle=False`` request is the one identity option whose rendered bytes the
server refuses. The execution matrix therefore exercises ``CYCLE`` -- with the
``MAXVALUE`` Oracle requires of a cycling ascending sequence -- not
``NO CYCLE``.
"""

import uuid

import pytest

from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.dialect.mixins.identity_column import (
    IdentityColumnMixin,
)
from rhosocial.activerecord.backend.expression import (
    ColumnDefinition,
    CreateTableExpression,
)
from rhosocial.activerecord.backend.expression.execution_testing import (
    ExecutionOutcome,
    classify_execution,
    confirm_expression_execution,
)
from rhosocial.activerecord.backend.expression.objects import Table
from rhosocial.activerecord.backend.expression.statements import (
    AutoIncrementClause,
    IdentityClause,
)
from rhosocial.activerecord.backend.expression.types import IntegerType
from rhosocial.activerecord.backend.impl.oracle.dialect import OracleDialect
from rhosocial.activerecord.base import IdentityAttribute

#: The six parameter probes the identity clause consults, one per option.
IDENTITY_OPTION_PROBES = (
    "supports_identity_generation_always",
    "supports_identity_start",
    "supports_identity_increment",
    "supports_identity_minvalue",
    "supports_identity_maxvalue",
    "supports_identity_cycle",
)

#: One execution case: name, the AR-layer attribute the model path carries,
#: and the clause fragment the rendered CREATE TABLE must contain before it is
#: sent to the server. The first three are the plan's cases; ``full_options``
#: is what gives the minvalue / maxvalue / cycle probes execution evidence.
EXECUTION_CASES = (
    ("bare", IdentityAttribute(), "GENERATED BY DEFAULT AS IDENTITY"),
    ("always", IdentityAttribute(generation="ALWAYS"), "GENERATED ALWAYS AS IDENTITY"),
    (
        "start_increment",
        IdentityAttribute(start=100, increment=5),
        "GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5)",
    ),
    (
        "full_options",
        IdentityAttribute(
            start=100, increment=5, minvalue=1, maxvalue=999999, cycle=True
        ),
        "GENERATED BY DEFAULT AS IDENTITY "
        "(START WITH 100 INCREMENT BY 5 MINVALUE 1 MAXVALUE 999999 CYCLE)",
    ),
)

#: A deliberately malformed identity clause. The sentinel exercises the
#: mechanism under test, not just any garbage: the rejection it produces
#: proves this server refuses a bad identity clause on this connection.
MALFORMED_IDENTITY_SENTINEL = (
    'CREATE TABLE "AR_IDENTITY_SENTINEL" (id NUMBER GENERATED SOMETIMES AS IDENTITY)'
)


def _oracle(version=(19, 0, 0)) -> OracleDialect:
    return OracleDialect(version=version)


def _create_table_with_identity(dialect, table_name, attribute):
    """The model-shaped path: the attribute is wrapped into an IdentityClause."""
    return CreateTableExpression(
        dialect=dialect,
        table=Table(dialect, table_name),
        columns=[
            ColumnDefinition(dialect, "id", IntegerType(dialect), attributes=[attribute])
        ],
    )


def _drop_block(table_name):
    """Teardown that survives a CREATE the server rejected.

    Oracle has no ``DROP TABLE IF EXISTS`` on 18c/21c, and a plain DROP in the
    helper's ``finally`` would replace the confirmation error with ORA-00942
    when the CREATE itself was refused -- hiding the verdict that matters.
    """
    quoted = f'"{table_name.upper()}"'
    return (
        f"BEGIN EXECUTE IMMEDIATE 'DROP TABLE {quoted} PURGE'; "
        f"EXCEPTION WHEN OTHERS THEN NULL; END;",
        (),
    )


class TestOracleIdentityDeclaration:
    """The probes state Oracle's real capability, with the 12c boundary."""

    def test_master_probe_is_version_gated_at_12c(self):
        assert _oracle((11, 2, 0)).supports_identity_column() is False
        assert _oracle((12, 1, 0)).supports_identity_column() is True
        assert _oracle((18, 0, 0)).supports_identity_column() is True
        assert _oracle((23, 0, 0)).supports_identity_column() is True

    @pytest.mark.parametrize("probe", IDENTITY_OPTION_PROBES)
    def test_every_identity_option_probe_is_true(self, probe):
        assert getattr(_oracle((19, 0, 0)), probe)() is True

    def test_auto_increment_marker_probe_is_false(self):
        """Oracle has no ``AUTO_INCREMENT`` marker; identity is its mechanism."""
        assert _oracle((23, 0, 0)).supports_auto_increment_column() is False

    def test_old_ambiguous_auto_increment_probe_is_gone(self):
        """The removed core probe must not linger as a second, dead answer."""
        assert not hasattr(_oracle((23, 0, 0)), "supports_auto_increment")


class TestOracleIdentityRender:
    """Oracle inherits core's formatter and renders the standard spelling."""

    def test_core_formatter_is_used_unchanged(self):
        """Oracle does not override ``format_identity_clause``."""
        assert (
            OracleDialect.format_identity_clause
            is IdentityColumnMixin.format_identity_clause
        )

    def test_bare_renders_by_default(self):
        sql, params = IdentityClause(_oracle()).to_sql()
        assert sql == " GENERATED BY DEFAULT AS IDENTITY"
        assert params == ()

    def test_always_renders(self):
        sql, params = IdentityClause(_oracle(), "ALWAYS").to_sql()
        assert sql == " GENERATED ALWAYS AS IDENTITY"
        assert params == ()

    def test_start_and_increment_render(self):
        sql, params = IdentityClause(_oracle(), start=100, increment=5).to_sql()
        assert sql == (
            " GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5)"
        )
        assert params == ()

    def test_bounds_and_positive_cycle_render(self):
        sql, params = IdentityClause(
            _oracle(),
            start=100,
            increment=5,
            minvalue=1,
            maxvalue=999999,
            cycle=True,
        ).to_sql()
        assert sql == (
            " GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5 "
            "MINVALUE 1 MAXVALUE 999999 CYCLE)"
        )
        assert params == ()

    def test_below_12c_the_clause_is_refused_by_name(self):
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            IdentityClause(_oracle((11, 2, 0))).to_sql()

    def test_auto_increment_marker_fails_closed(self):
        with pytest.raises(UnsupportedFeatureError, match="AUTO_INCREMENT column"):
            AutoIncrementClause(_oracle((23, 0, 0))).to_sql()

    def test_formatter_consults_oracle_probes_per_option(self):
        """Withdrawing one probe refuses that option only -- on this dialect."""

        class OracleWithoutStart(OracleDialect):
            def supports_identity_start(self) -> bool:
                return False

        dialect = OracleWithoutStart(version=(19, 0, 0))
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY START"):
            IdentityClause(dialect, start=10).to_sql()
        # The other options keep rendering: the gate is per option, not a
        # blanket switch that would make the per-option probes decorative.
        sql, _ = IdentityClause(dialect, increment=5).to_sql()
        assert "INCREMENT BY 5" in sql


class TestOracleIdentityExecution:
    """The rendered CREATE TABLE is accepted by live 18c / 21c / 23c."""

    @pytest.mark.parametrize(
        "case_name,attribute,fragment",
        EXECUTION_CASES,
        ids=[case[0] for case in EXECUTION_CASES],
    )
    def test_rendered_create_table_is_accepted_by_the_server(
        self, oracle_backend, case_name, attribute, fragment
    ):
        backend = oracle_backend
        dialect = backend.dialect

        # Sentinel first, on the same connection: the channel must be able to
        # report a rejection before its acceptance means anything.
        assert (
            classify_execution(backend, MALFORMED_IDENTITY_SENTINEL)
            is ExecutionOutcome.REJECTED
        )
        assert (
            classify_execution(backend, "THIS IS NOT SQL")
            is ExecutionOutcome.REJECTED
        )

        table_name = f"AR_ID_{case_name}_{uuid.uuid4().hex[:8]}"
        expression = _create_table_with_identity(dialect, table_name, attribute)
        sql, _ = expression.to_sql()
        assert fragment in sql, sql

        outcome = confirm_expression_execution(
            backend, expression, teardown=[_drop_block(table_name)]
        )
        assert outcome is not ExecutionOutcome.NOT_RENDERED, (
            f"Oracle {dialect.version} declares identity support yet refused to "
            f"render: {sql}"
        )
        assert outcome is ExecutionOutcome.ACCEPTED

    def test_live_declaration_matches_the_server(self, oracle_backend):
        """The adapted dialect answers the same probes the server confirms."""
        dialect = oracle_backend.dialect
        assert dialect.version >= (12, 0, 0), (
            f"scenario sanity: the identity cases require 12c+, got {dialect.version}"
        )
        assert dialect.supports_identity_column() is True
        for probe in IDENTITY_OPTION_PROBES:
            assert getattr(dialect, probe)() is True, probe
        assert dialect.supports_auto_increment_column() is False
