# tests/rhosocial/activerecord_oracle_test/feature/backend/test_oracle_identity_conformance.py
"""Oracle identity-column conformance: declaration, renderer, and execution.

Oracle accepts the SQL-standard ``GENERATED ... AS IDENTITY`` clause from 12c
on and declares every option the clause carries. The formatter stays core's --
Oracle does not override ``format_identity_clause``, so the gating keeps living
in one place. Oracle's grammar differs only in spelling, so the three
``identity_*_keyword`` hooks are overridden instead: ``NOCYCLE`` / ``NOORDER``
/ ``NOCACHE``, each measured on live 18c / 21c / 23c. Core's spaced
``NO CYCLE`` / ``NO ORDER`` / ``NO CACHE`` are refused by every measured
server (ORA-02000), and ``CACHE 0`` is refused too (ORA-04010), which is why
the falsy cache count spells ``NOCACHE``.

The column-definition order is Oracle's grammar: ``col type
[VISIBLE|INVISIBLE] [GENERATED ... AS IDENTITY [(options)]] [inline_constraint
...]``. The previous constraints-first order rendered ``PRIMARY KEY GENERATED
...`` and ``... AS IDENTITY INVISIBLE``, both refused on every measured server
(ORA-00907 on 18c / 21c, ORA-03076 on 23c).

Rendering is not execution. The unit tests below pin the declaration and the
rendered bytes; the execution tests then send the rendered ``CREATE TABLE`` to
live 18c / 21c / 23c. Every live verdict runs sentinels first on the same
connection -- ``THIS IS NOT SQL`` must be REJECTED and ``SELECT 1 FROM DUAL``
must be ACCEPTED -- because an ``ACCEPTED`` that has never been contrasted with
a rejection is not evidence.

The legacy ``is_auto_increment`` constraint path routes through the gated
formatter: Oracle 12+ renders the same identity clause as before, while Oracle
< 12 refuses by name instead of silently dropping the clause. The live servers
are all 12+, so the below-12 refusal is a dialect-level test and the live case
covers 12+.
"""

import uuid

import pytest

from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.dialect.mixins.identity_column import (
    IdentityColumnMixin,
)
from rhosocial.activerecord.backend.expression import (
    ColumnConstraint,
    ColumnConstraintType,
    ColumnDefinition,
    CreateTableExpression,
)
from rhosocial.activerecord.backend.expression.execution_testing import (
    ExecutionOutcome,
    classify_execution,
    confirm_expression_execution,
)
from rhosocial.activerecord.backend.expression.objects import Table
from rhosocial.activerecord.backend.expression.statements import (
    AutoIncrementClause,
    IdentityClause,
)
from rhosocial.activerecord.backend.expression.types import IntegerType
from rhosocial.activerecord.backend.impl.oracle.dialect import OracleDialect
from rhosocial.activerecord.backend.impl.oracle.expression import (
    OracleColumnDefinition,
)
from rhosocial.activerecord.base import IdentityAttribute

#: The eight parameter probes the identity clause consults, one per option.
IDENTITY_OPTION_PROBES = (
    "supports_identity_generation_always",
    "supports_identity_start",
    "supports_identity_increment",
    "supports_identity_minvalue",
    "supports_identity_maxvalue",
    "supports_identity_cycle",
    "supports_identity_order",
    "supports_identity_cache",
)

#: One execution case: name, the AR-layer attribute the model path carries,
#: and the clause fragment the rendered CREATE TABLE must contain before it is
#: sent to the server. ``cycle_false`` is the spelling fix this round closes.
EXECUTION_CASES = (
    ("bare", IdentityAttribute(), "GENERATED BY DEFAULT AS IDENTITY"),
    ("always", IdentityAttribute(generation="ALWAYS"), "GENERATED ALWAYS AS IDENTITY"),
    (
        "start_increment",
        IdentityAttribute(start=100, increment=5),
        "GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5)",
    ),
    (
        "full_options",
        IdentityAttribute(
            start=100, increment=5, minvalue=1, maxvalue=999999, cycle=True
        ),
        "GENERATED BY DEFAULT AS IDENTITY "
        "(START WITH 100 INCREMENT BY 5 MINVALUE 1 MAXVALUE 999999 CYCLE)",
    ),
    (
        "cycle_false",
        IdentityAttribute(cycle=False),
        "GENERATED BY DEFAULT AS IDENTITY (NOCYCLE)",
    ),
)

#: Clause-level option cases. The AR-layer ``IdentityAttribute`` has no
#: order/cache fields, so these are requested through ``IdentityClause`` and
#: the rendered clause is embedded in the CREATE TABLE the server must accept.
OPTION_CLAUSE_CASES = (
    ("order_true", {"order": True}, "GENERATED BY DEFAULT AS IDENTITY (ORDER)"),
    ("no_order", {"no_order": True}, "GENERATED BY DEFAULT AS IDENTITY (NOORDER)"),
    ("cache_10", {"cache": 10}, "GENERATED BY DEFAULT AS IDENTITY (CACHE 10)"),
    ("no_cache", {"no_cache": True}, "GENERATED BY DEFAULT AS IDENTITY (NOCACHE)"),
)

#: A deliberately malformed identity clause. The sentinel exercises the
#: mechanism under test, not just any garbage: the rejection it produces
#: proves this server refuses a bad identity clause on this connection.
MALFORMED_IDENTITY_SENTINEL = (
    'CREATE TABLE "AR_IDENTITY_SENTINEL" (id NUMBER GENERATED SOMETIMES AS IDENTITY)'
)


def _oracle(version=(19, 0, 0)) -> OracleDialect:
    return OracleDialect(version=version)


def _column(dialect, *, name="id", attribute=None, constraints=(), invisible=False):
    """One identity column; ``OracleColumnDefinition`` when INVISIBLE is asked."""
    column_class = OracleColumnDefinition if invisible else ColumnDefinition
    kwargs = {}
    if attribute is not None:
        kwargs["attributes"] = [attribute]
    if invisible:
        kwargs["invisible"] = True
    return column_class(
        dialect, name, IntegerType(dialect), constraints=list(constraints), **kwargs
    )


def _pk_constraint(dialect, *, is_auto_increment=False):
    return ColumnConstraint(
        dialect,
        ColumnConstraintType.PRIMARY_KEY,
        is_auto_increment=is_auto_increment,
    )


def _create_table_with_identity(dialect, table_name, attribute):
    """The model-shaped path: the attribute is wrapped into an IdentityClause."""
    return CreateTableExpression(
        dialect=dialect,
        table=Table(dialect, table_name),
        columns=[_column(dialect, attribute=attribute)],
    )


def _drop_block(table_name):
    """Teardown that survives a CREATE the server rejected.

    Oracle has no ``DROP TABLE IF EXISTS`` on 18c/21c, and a plain DROP in the
    helper's ``finally`` would replace the confirmation error with ORA-00942
    when the CREATE itself was refused -- hiding the verdict that matters.
    """
    quoted = f'"{table_name.upper()}"'
    return (
        f"BEGIN EXECUTE IMMEDIATE 'DROP TABLE {quoted} PURGE'; "
        f"EXCEPTION WHEN OTHERS THEN NULL; END;",
        (),
    )


def _assert_channel(backend):
    """Sentinels on the same connection, before any verdict is trusted."""
    assert (
        classify_execution(backend, "THIS IS NOT SQL") is ExecutionOutcome.REJECTED
    )
    assert (
        classify_execution(backend, "SELECT 1 FROM DUAL")
        is ExecutionOutcome.ACCEPTED
    )
    assert (
        classify_execution(backend, MALFORMED_IDENTITY_SENTINEL)
        is ExecutionOutcome.REJECTED
    )


def _confirm(backend, expression, table_name):
    return confirm_expression_execution(
        backend, expression, teardown=[_drop_block(table_name)]
    )


class TestOracleIdentityDeclaration:
    """The probes state Oracle's real capability, with the 12c boundary."""

    def test_master_probe_is_version_gated_at_12c(self):
        assert _oracle((11, 2, 0)).supports_identity_column() is False
        assert _oracle((12, 1, 0)).supports_identity_column() is True
        assert _oracle((18, 0, 0)).supports_identity_column() is True
        assert _oracle((23, 0, 0)).supports_identity_column() is True

    @pytest.mark.parametrize("probe", IDENTITY_OPTION_PROBES)
    def test_every_identity_option_probe_is_true(self, probe):
        assert getattr(_oracle((19, 0, 0)), probe)() is True

    def test_auto_increment_marker_probe_is_false(self):
        """Oracle has no ``AUTO_INCREMENT`` marker; identity is its mechanism."""
        assert _oracle((23, 0, 0)).supports_auto_increment_column() is False

    def test_old_ambiguous_auto_increment_probe_is_gone(self):
        """The removed core probe must not linger as a second, dead answer."""
        assert not hasattr(_oracle((23, 0, 0)), "supports_auto_increment")


class TestOracleIdentityRender:
    """Oracle inherits core's formatter and overrides the spelling hooks only."""

    def test_core_formatter_is_used_unchanged(self):
        """Oracle does not override ``format_identity_clause``."""
        assert (
            OracleDialect.format_identity_clause
            is IdentityColumnMixin.format_identity_clause
        )

    def test_spelling_hooks_are_overridden(self):
        """Spelling moves to the hooks; gating stays in the formatter."""
        for hook in (
            "identity_cycle_keyword",
            "identity_order_keyword",
            "identity_cache_keyword",
        ):
            assert getattr(OracleDialect, hook) is not getattr(
                IdentityColumnMixin, hook
            ), hook

    def test_bare_renders_by_default(self):
        sql, params = IdentityClause(_oracle()).to_sql()
        assert sql == " GENERATED BY DEFAULT AS IDENTITY"
        assert params == ()

    def test_always_renders(self):
        sql, params = IdentityClause(_oracle(), "ALWAYS").to_sql()
        assert sql == " GENERATED ALWAYS AS IDENTITY"
        assert params == ()

    def test_start_and_increment_render(self):
        sql, params = IdentityClause(_oracle(), start=100, increment=5).to_sql()
        assert sql == (
            " GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5)"
        )
        assert params == ()

    def test_bounds_and_positive_cycle_render(self):
        sql, params = IdentityClause(
            _oracle(),
            start=100,
            increment=5,
            minvalue=1,
            maxvalue=999999,
            cycle=True,
        ).to_sql()
        assert sql == (
            " GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5 "
            "MINVALUE 1 MAXVALUE 999999 CYCLE)"
        )
        assert params == ()

    def test_negative_cycle_spells_nocycle(self):
        """Core's spaced ``NO CYCLE`` is refused; ``NOCYCLE`` is Oracle's form."""
        sql, params = IdentityClause(_oracle(), no_cycle=True).to_sql()
        assert sql == " GENERATED BY DEFAULT AS IDENTITY (NOCYCLE)"
        assert params == ()

    def test_order_options_spell_order_and_noorder(self):
        sql, _ = IdentityClause(_oracle(), order=True).to_sql()
        assert sql == " GENERATED BY DEFAULT AS IDENTITY (ORDER)"
        sql, _ = IdentityClause(_oracle(), no_order=True).to_sql()
        assert sql == " GENERATED BY DEFAULT AS IDENTITY (NOORDER)"

    def test_cache_options_spell_cache_and_nocache(self):
        sql, _ = IdentityClause(_oracle(), cache=10).to_sql()
        assert sql == " GENERATED BY DEFAULT AS IDENTITY (CACHE 10)"
        sql, _ = IdentityClause(_oracle(), no_cache=True).to_sql()
        assert sql == " GENERATED BY DEFAULT AS IDENTITY (NOCACHE)"

    def test_pk_and_identity_render_identity_first(self):
        """Identity precedes the inline constraint, as Oracle's grammar wants."""
        dialect = _oracle()
        expression = CreateTableExpression(
            dialect=dialect,
            table=Table(dialect, "pk_identity"),
            columns=[
                _column(
                    dialect,
                    attribute=IdentityAttribute(),
                    constraints=[_pk_constraint(dialect)],
                )
            ],
        )
        sql, _ = expression.to_sql()
        assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql, sql

    def test_invisible_identity_renders_in_grammar_order(self):
        """``INVISIBLE`` follows the type and precedes the identity clause."""
        dialect = _oracle()
        expression = CreateTableExpression(
            dialect=dialect,
            table=Table(dialect, "invisible_identity"),
            columns=[
                _column(
                    dialect,
                    attribute=IdentityAttribute(),
                    constraints=[_pk_constraint(dialect)],
                    invisible=True,
                )
            ],
        )
        sql, _ = expression.to_sql()
        assert "INVISIBLE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql, sql

    def test_below_12c_the_clause_is_refused_by_name(self):
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            IdentityClause(_oracle((11, 2, 0))).to_sql()

    def test_auto_increment_marker_fails_closed(self):
        with pytest.raises(UnsupportedFeatureError, match="AUTO_INCREMENT column"):
            AutoIncrementClause(_oracle((23, 0, 0))).to_sql()

    def test_formatter_consults_oracle_probes_per_option(self):
        """Withdrawing one probe refuses that option only -- on this dialect."""

        class OracleWithoutStart(OracleDialect):
            def supports_identity_start(self) -> bool:
                return False

        dialect = OracleWithoutStart(version=(19, 0, 0))
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY START"):
            IdentityClause(dialect, start=10).to_sql()
        # The other options keep rendering: the gate is per option, not a
        # blanket switch that would make the per-option probes decorative.
        sql, _ = IdentityClause(dialect, increment=5).to_sql()
        assert "INCREMENT BY 5" in sql


class TestOracleLegacyAutoIncrement:
    """The legacy ``is_auto_increment`` constraint routes through the gate."""

    def _legacy_table(self, dialect, table_name):
        return CreateTableExpression(
            dialect=dialect,
            table=Table(dialect, table_name),
            columns=[
                _column(
                    dialect,
                    constraints=[
                        _pk_constraint(dialect, is_auto_increment=True)
                    ],
                )
            ],
        )

    def test_above_12c_renders_the_gated_clause(self):
        sql, _ = self._legacy_table(_oracle((19, 0, 0)), "legacy").to_sql()
        assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql, sql

    def test_below_12c_refuses_by_name_instead_of_dropping(self):
        """Oracle < 12 must raise, not silently render a column without identity."""
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            self._legacy_table(_oracle((11, 2, 0)), "legacy").to_sql()


class TestOracleIdentityExecution:
    """The rendered CREATE TABLE is accepted by live 18c / 21c / 23c."""

    @pytest.mark.parametrize(
        "case_name,attribute,fragment",
        EXECUTION_CASES,
        ids=[case[0] for case in EXECUTION_CASES],
    )
    def test_rendered_create_table_is_accepted_by_the_server(
        self, oracle_backend, case_name, attribute, fragment
    ):
        backend = oracle_backend
        dialect = backend.dialect

        # Sentinels first, on the same connection: the channel must be able to
        # report a rejection before its acceptance means anything.
        _assert_channel(backend)

        table_name = f"AR_ID_{case_name}_{uuid.uuid4().hex[:8]}"
        expression = _create_table_with_identity(dialect, table_name, attribute)
        sql, _ = expression.to_sql()
        assert fragment in sql, sql

        outcome = _confirm(backend, expression, table_name)
        assert outcome is not ExecutionOutcome.NOT_RENDERED, (
            f"Oracle {dialect.version} declares identity support yet refused to "
            f"render: {sql}"
        )
        assert outcome is ExecutionOutcome.ACCEPTED

    def test_live_declaration_matches_the_server(self, oracle_backend):
        """The adapted dialect answers the same probes the server confirms."""
        dialect = oracle_backend.dialect
        assert dialect.version >= (12, 0, 0), (
            f"scenario sanity: the identity cases require 12c+, got {dialect.version}"
        )
        assert dialect.supports_identity_column() is True
        for probe in IDENTITY_OPTION_PROBES:
            assert getattr(dialect, probe)() is True, probe
        assert dialect.supports_auto_increment_column() is False


class TestOracleIdentityColumnShapes:
    """The full column shapes the reordered formatter produces execute live."""

    def test_primary_key_and_identity_execute(self, oracle_backend):
        """``PK + identity`` used to render ``PRIMARY KEY GENERATED ...``."""
        backend = oracle_backend
        dialect = backend.dialect
        _assert_channel(backend)

        table_name = f"AR_ID_PK_{uuid.uuid4().hex[:8]}"
        expression = CreateTableExpression(
            dialect=dialect,
            table=Table(dialect, table_name),
            columns=[
                _column(
                    dialect,
                    attribute=IdentityAttribute(),
                    constraints=[_pk_constraint(dialect)],
                )
            ],
        )
        sql, _ = expression.to_sql()
        assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql, sql
        assert _confirm(backend, expression, table_name) is ExecutionOutcome.ACCEPTED

    def test_invisible_identity_executes(self, oracle_backend):
        """The new order puts INVISIBLE after the type, before the identity clause."""
        backend = oracle_backend
        dialect = backend.dialect
        _assert_channel(backend)

        table_name = f"AR_ID_INV_{uuid.uuid4().hex[:8]}"
        expression = CreateTableExpression(
            dialect=dialect,
            table=Table(dialect, table_name),
            columns=[
                _column(
                    dialect,
                    attribute=IdentityAttribute(),
                    constraints=[_pk_constraint(dialect)],
                    invisible=True,
                ),
                # A second, visible column is required: a table whose only
                # column is invisible is refused (ORA-54039) on all three
                # servers, which would mask the grammar verdict.
                _column(dialect, name="other"),
            ],
        )
        sql, _ = expression.to_sql()
        assert "INVISIBLE GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql, sql
        assert _confirm(backend, expression, table_name) is ExecutionOutcome.ACCEPTED

    def test_legacy_auto_increment_executes(self, oracle_backend):
        """The legacy path renders the same gated clause above 12c."""
        backend = oracle_backend
        dialect = backend.dialect
        _assert_channel(backend)

        table_name = f"AR_ID_LEGACY_{uuid.uuid4().hex[:8]}"
        expression = CreateTableExpression(
            dialect=dialect,
            table=Table(dialect, table_name),
            columns=[
                _column(
                    dialect,
                    constraints=[
                        _pk_constraint(dialect, is_auto_increment=True)
                    ],
                )
            ],
        )
        sql, _ = expression.to_sql()
        assert "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql, sql
        assert _confirm(backend, expression, table_name) is ExecutionOutcome.ACCEPTED


class TestOracleIdentityOptionClauses:
    """Clause-level order/cache renderings are accepted by the live server.

    The AR-layer ``IdentityAttribute`` has no order/cache fields, so the
    options are requested through ``IdentityClause`` directly and the rendered
    clause is embedded in the CREATE TABLE under test. A declared option that
    refuses to render is a defect, not a skip: the refusal propagates from
    ``to_sql`` instead of being classified as a rejection.
    """

    @pytest.mark.parametrize(
        "case_name,kwargs,fragment",
        OPTION_CLAUSE_CASES,
        ids=[case[0] for case in OPTION_CLAUSE_CASES],
    )
    def test_rendered_option_clause_is_accepted(
        self, oracle_backend, case_name, kwargs, fragment
    ):
        backend = oracle_backend
        dialect = backend.dialect
        _assert_channel(backend)

        clause_sql, _ = IdentityClause(dialect, **kwargs).to_sql()
        assert fragment in clause_sql, clause_sql

        table_name = f"AR_ID_OPT_{case_name}_{uuid.uuid4().hex[:8]}"
        statement = f'CREATE TABLE "{table_name.upper()}" (id NUMBER{clause_sql})'
        try:
            outcome = classify_execution(backend, statement)
            assert outcome is ExecutionOutcome.ACCEPTED, statement
        finally:
            backend.execute(*_drop_block(table_name))
