"""
Quick Start: Connect to Oracle and execute queries.

This example demonstrates:
1. How to establish a connection to Oracle
2. How to view connection information
3. How to execute basic queries
4. How to handle transactions

Oracle Version Support: 12c+
"""

import os

from rhosocial.activerecord.backend.impl.oracle import (
    OracleBackend,
    OracleConnectionConfig,
)
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', 'localhost'),
    port=int(os.getenv('ORACLE_PORT', '1521')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'password'),
    service_name=os.getenv('ORACLE_SERVICE', 'XEPDB1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

dql_options = ExecutionOptions(stmt_type=StatementType.SELECT)
ddl_options = ExecutionOptions(stmt_type=StatementType.DDL)

print("=" * 60)
print("Connected to Oracle Database")
print("=" * 60)

version = backend.get_server_version()
print(f"Oracle Version: {'.'.join(map(str, version))}")
print(f"Host: {config.host}:{config.port}")
print(f"Service: {config.service_name}")
print(f"User: {config.username}")

result = backend.execute(
    "SELECT 'Hello from Oracle!' AS message FROM DUAL",
    options=dql_options
)
print(f"\nTest query result: {result.data[0]['message']}")

backend.execute("""
    CREATE TABLE quickstart_users (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        status VARCHAR2(20) DEFAULT 'active',
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP
    )
""", options=ddl_options)

backend.execute(
    "INSERT INTO quickstart_users (name, status) VALUES (:1, :2)",
    ('Alice', 'active'),
    options=ExecutionOptions(stmt_type=StatementType.INSERT)
)

backend.execute(
    "INSERT INTO quickstart_users (name, status) VALUES (:1, :2)",
    ('Bob', 'inactive'),
    options=ExecutionOptions(stmt_type=StatementType.INSERT)
)

result = backend.execute(
    "SELECT * FROM quickstart_users ORDER BY id",
    options=dql_options
)
print("\nUsers table:")
for row in result.data:
    print(f"  ID: {row['id']}, Name: {row['name']}, Status: {row['status']}")

with backend.transaction():
    backend.execute(
        "UPDATE quickstart_users SET status = :1 WHERE name = :2",
        ('active', 'Bob'),
        options=ExecutionOptions(stmt_type=StatementType.UPDATE)
    )

result = backend.execute(
    "SELECT * FROM quickstart_users WHERE name = :1",
    ('Bob',),
    options=dql_options
)
print(f"\nAfter transaction - Bob's status: {result.data[0]['status']}")

backend.execute("DROP TABLE quickstart_users PURGE", options=ddl_options)

backend.disconnect()

print("\n" + "=" * 60)
print("Quick start example completed successfully!")
print("=" * 60)
