"""
Aggregate and GROUP BY Queries.

This example demonstrates:
1. COUNT / SUM / AVG / MIN / MAX aggregations
2. GROUP BY with multiple columns
3. HAVING clause
4. Standard vs. analytic aggregates

Oracle Version Support: 12c+
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE agg_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        dept VARCHAR2(50) NOT NULL,
        role VARCHAR2(50) NOT NULL,
        salary NUMBER(10, 2) NOT NULL
    )
""", options=DDL)

for d, r, s in [
    ("Sales", "Manager", 80000), ("Sales", "Rep", 50000),
    ("Sales", "Rep", 52000), ("HR", "Manager", 75000),
    ("HR", "Coord", 45000), ("IT", "Manager", 95000),
    ("IT", "Dev", 72000), ("IT", "Dev", 68000),
]:
    backend.execute(
        "INSERT INTO agg_demo (dept, role, salary) VALUES (:1, :2, :3)",
        (d, r, s), options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )

print("=" * 60)
print("Aggregate Query Examples")
print("=" * 60)

print("\n[1] COUNT + SUM + AVG by department")
result = backend.execute(
    "SELECT dept, COUNT(*) AS cnt, SUM(salary) AS total, "
    "ROUND(AVG(salary), 2) AS avg_sal FROM agg_demo GROUP BY dept ORDER BY dept",
    options=DQL,
)
for row in result.data:
    print(f"  {row['dept']}: {row['cnt']} employees, total=${row['total']}, avg=${row['avg_sal']}")

print("\n[2] Multi-value aggregate (MIN/MAX)")
result = backend.execute(
    "SELECT dept, MIN(salary) AS min_sal, MAX(salary) AS max_sal "
    "FROM agg_demo GROUP BY dept ORDER BY dept",
    options=DQL,
)
for row in result.data:
    print(f"  {row['dept']}: min=${row['min_sal']}, max=${row['max_sal']}")

print("\n[3] GROUP BY dept, role")
result = backend.execute(
    "SELECT dept, role, COUNT(*) AS cnt, ROUND(AVG(salary), 2) AS avg_sal "
    "FROM agg_demo GROUP BY dept, role ORDER BY dept, role",
    options=DQL,
)
for row in result.data:
    print(f"  {row['dept']} / {row['role']}: {row['cnt']} person(s), avg=${row['avg_sal']}")

print("\n[4] HAVING (filter groups)")
result = backend.execute(
    "SELECT dept, COUNT(*) AS cnt FROM agg_demo GROUP BY dept "
    "HAVING COUNT(*) > 2 ORDER BY dept",
    options=DQL,
)
for row in result.data:
    print(f"  {row['dept']}: {row['cnt']} (departments with >2 employees)")

backend.execute("DROP TABLE agg_demo PURGE", options=DDL)
backend.disconnect()
print("\nAggregate examples completed successfully.")