"""
Basic SELECT and Expression Queries.

This example demonstrates:
1. SELECT all
2. SELECT specific columns with WHERE
3. Expression-based SELECT (build QueryExpression, print SQL, then execute)
4. SELECT with aggregate

Oracle Version Support: 12c+
"""

import os
import re

from rhosocial.activerecord.backend.expression import QueryExpression, TableExpression, WhereClause
from rhosocial.activerecord.backend.expression.core import Column, Literal
from rhosocial.activerecord.backend.expression.predicates import ComparisonPredicate
from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()
dialect = backend.dialect

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

try:
    backend.execute("DROP TABLE eg_query_basic PURGE", options=DDL)
except Exception:
    pass

backend.execute("""
    CREATE TABLE eg_query_basic (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        product VARCHAR2(100) NOT NULL,
        category VARCHAR2(50),
        price NUMBER(10, 2) NOT NULL,
        in_stock NUMBER(1) DEFAULT 1
    )
""", options=DDL)

for p, c, pr, st in [
    ("Widget A", "tools", 19.99, 1),
    ("Widget B", "tools", 29.99, 0),
    ("Gadget X", "gadgets", 49.99, 1),
    ("Gadget Y", "gadgets", 59.99, 1),
    ("Tool Z", "tools", 9.99, 1),
]:
    backend.execute(
        "INSERT INTO eg_query_basic (product, category, price, in_stock) VALUES (:1, :2, :3, :4)",
        (p, c, pr, st),
        options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )

print("=" * 60)
print("Basic Query Examples")
print("=" * 60)

print("\n[1] SELECT all (inline SQL)")
result = backend.execute(
    "SELECT * FROM eg_query_basic ORDER BY id", options=DQL,
)
for row in result.data:
    print(f"  {row['product']}: {row['category']} ${row['price']} "
          f"({'in stock' if row['in_stock'] else 'out of stock'})")

print("\n[2] SELECT specific columns with WHERE")
result = backend.execute(
    "SELECT product, price FROM eg_query_basic WHERE category = :1 ORDER BY price",
    ("tools",), options=DQL,
)
for row in result.data:
    print(f"  {row['product']} ${row['price']}")

print("\n[3] Expression-based SELECT (build -> print -> execute)")
src = TableExpression(dialect, "eg_query_basic")
pred = ComparisonPredicate(dialect, "=", Column(dialect, "category"), Literal(dialect, "gadgets"))
qry = QueryExpression(
    dialect=dialect,
    from_=src,
    select=[Column(dialect, "product"), Column(dialect, "price")],
    where=WhereClause(dialect, pred),
)
gen_sql, gen_params = qry.to_sql()
print(f"  Generated SQL: {gen_sql}")
# Oracle driver renumbers `?` -> `:1, :2, ...` at execute time
result = backend.execute(gen_sql, gen_params, options=DQL)
for row in result.data:
    print(f"  {row['product']} ${row['price']}")

print("\n[4] SELECT with aggregate (inline SQL)")
result = backend.execute(
    "SELECT category, COUNT(*) AS cnt, AVG(price) AS avg_price "
    "FROM eg_query_basic GROUP BY category ORDER BY category",
    options=DQL,
)
for row in result.data:
    avg = row['avg_price']
    try:
        avg_val = float(avg)
    except (TypeError, ValueError):
        avg_val = 0.0
    print(f"  {row['category']}: count={row['cnt']}, avg_price=${avg_val:.2f}")

try:
    backend.execute("DROP TABLE eg_query_basic PURGE", options=DDL)
except Exception:
    pass
backend.disconnect()
print("\nBasic query examples completed successfully.")