"""
WITH / Common Table Expressions (CTE).

This example demonstrates:
1. Simple CTE with one subquery
2. Multi-level CTE (nested)
3. Recursive WITH (hierarchical, numeric generation)

Oracle Version Support: 12c+ (WITH clause since Oracle 9i, recursive since 11gR2)
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE cte_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        parent_id NUMBER,
        name VARCHAR2(100) NOT NULL
    )
""", options=DDL)

rows = [
    (None, "CEO"),
    (1, "VP Sales"),
    (1, "VP Engineering"),
    (2, "Sales Lead"),
    (3, "Senior Dev"),
    (3, "Junior Dev"),
]
for parent, name in rows:
    backend.execute(
        "INSERT INTO cte_demo (parent_id, name) VALUES (:1, :2)",
        (parent, name), options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )

print("=" * 60)
print("CTE (WITH) Query Examples")
print("=" * 60)

print("\n[1] Simple CTE")
result = backend.execute(
    "WITH top_org AS (SELECT name FROM cte_demo WHERE parent_id IS NULL) "
    "SELECT name FROM top_org",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}")

print("\n[2] Multi-level CTE")
result = backend.execute(
    "WITH top AS (SELECT id, name FROM cte_demo WHERE parent_id IS NULL), "
    "second AS (SELECT c.name FROM cte_demo c, top t WHERE c.parent_id = t.id) "
    "SELECT name FROM top UNION ALL SELECT name FROM second",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}")

print("\n[3] Recursive WITH (org-chart)")
result = backend.execute(
    "WITH org_chart (id, name, depth) AS ("
    "    SELECT id, name, 1 FROM cte_demo WHERE parent_id IS NULL "
    "    UNION ALL "
    "    SELECT e.id, e.name, oc.depth + 1 "
    "    FROM cte_demo e, org_chart oc WHERE e.parent_id = oc.id"
    ") "
    "SEARCH DEPTH FIRST BY id SET ord "
    "SELECT name, depth FROM org_chart ORDER BY ord",
    options=DQL,
)
for row in result.data:
    indent = "  " * (row['depth'] - 1)
    print(f"  {indent}{row['name']}")

print("\n[4] Recursive WITH (Fibonacci)")
result = backend.execute(
    "WITH fib (n, a, b) AS ("
    "    SELECT 1, 0, 1 FROM DUAL "
    "    UNION ALL "
    "    SELECT n + 1, b, a + b FROM fib WHERE n < 10"
    ") SELECT n, a AS fib_n FROM fib",
    options=DQL,
)
for row in result.data:
    print(f"  fib({row['n']}) = {row['fib_n']}")

backend.execute("DROP TABLE cte_demo PURGE", options=DDL)
backend.disconnect()
print("\nCTE examples completed successfully.")