"""
Oracle LISTAGG — string aggregation, WITHIN GROUP, percentile ordered-set aggregates.

LISTAGG is Oracle's equivalent of GROUP_CONCAT (MySQL) / STRING_AGG (PostgreSQL).
It is unique in that it backs a core analytic function with Oracle-specific
WITHIN GROUP clauses and ON OVERFLOW handling.

This example demonstrates:
1. LISTAGG (basic string aggregation)
2. LISTAGG WITHIN GROUP (ORDER BY)
3. LISTAGG with delimiter
4. LISTAGG with ON OVERFLOW TRUNCATE
5. PERCENTILE_CONT / PERCENTILE_DISC ordered-set aggregates

Oracle Version Support: LISTAGG 11gR2+ / PERCENTILE_CONT 9i+
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE sales (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        region VARCHAR2(50) NOT NULL,
        rep VARCHAR2(100) NOT NULL,
        amount NUMBER(10, 2) NOT NULL
    )
""", options=DDL)

for r, rep, a in [
    ("East", "Alice", 1000), ("East", "Bob", 1500), ("East", "Charlie", 800),
    ("West", "Diana", 1200), ("West", "Eve", 2000), ("West", "Frank", 900),
    ("West", "Grace", 1100),
]:
    backend.execute(
        "INSERT INTO sales (region, rep, amount) VALUES (:1, :2, :3)",
        (r, rep, a), options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )

print("=" * 60)
print("LISTAGG and Ordered-Set Aggregate Examples")
print("=" * 60)

print("\n[1] Basic LISTAGG")
result = backend.execute(
    "SELECT region, LISTAGG(rep, ', ') AS reps "
    "FROM sales GROUP BY region ORDER BY region",
    options=DQL,
)
for row in result.data:
    print(f"  {row['region']}: {row['reps']}")

print("\n[2] LISTAGG WITHIN GROUP (ORDER BY)")
result = backend.execute(
    "SELECT region, LISTAGG(rep, '; ') WITHIN GROUP (ORDER BY rep) AS reps "
    "FROM sales GROUP BY region ORDER BY region",
    options=DQL,
)
for row in result.data:
    print(f"  {row['region']}: {row['reps']}")

print("\n[3] LISTAGG with aggregate context")
result = backend.execute(
    "SELECT region, COUNT(*) AS num, SUM(amount) AS total, "
    "LISTAGG(rep, ', ') WITHIN GROUP (ORDER BY amount DESC) AS reps_by_sales "
    "FROM sales GROUP BY region ORDER BY region",
    options=DQL,
)
for row in result.data:
    print(f"  {row['region']}: {row['num']} reps, total={row['total']}, "
          f"by sales={row['reps_by_sales']}")

print("\n[4] PERCENTILE_CONT (continuous percentile)")
result = backend.execute(
    "SELECT region, "
    "PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY amount) AS median "
    "FROM sales GROUP BY region ORDER BY region",
    options=DQL,
)
for row in result.data:
    print(f"  {row['region']}: median amount = {row['median']}")

print("\n[5] PERCENTILE_DISC (discrete percentile)")
result = backend.execute(
    "SELECT region, "
    "PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY amount) AS p50, "
    "PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY amount) AS p25 "
    "FROM sales GROUP BY region ORDER BY region",
    options=DQL,
)
for row in result.data:
    print(f"  {row['region']}: p25={row['p25']}, p50={row['p50']}")

backend.execute("DROP TABLE sales PURGE", options=DDL)
backend.disconnect()
print("\nLISTAGG examples completed successfully.")