"""
Pagination — OFFSET / FETCH FIRST n ROWS ONLY.

Oracle 12c+ supports the standard ANSI SQL OFFSET/FETCH NEXT syntax.
Before 12c, Oracle only supported ROWNUM (pseudo-column) for pagination.

This example demonstrates:
1. Row number via ROWNUM (traditional Oracle approach)
2. OFFSET ... ROWS FETCH NEXT ... ROWS ONLY (ANSI syntax, 12c+)
3. FETCH FIRST ... ROWS ONLY (top-N without offset)
4. FETCH ... PERCENT (percentile-based paging)

Oracle Version Support: 12c+ (OFFSET/FETCH NEXT only in 12c+)
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE page_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        score NUMBER(5) NOT NULL
    )
""", options=DDL)

names = ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace",
         "Henry", "Iris", "Jack", "Karen", "Leo"]
for i, n in enumerate(names):
    backend.execute(
        "INSERT INTO page_demo (name, score) VALUES (:1, :2)",
        (n, (i + 1) * 10),
        options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )

print("=" * 60)
print("Pagination Examples")
print("=" * 60)

print("\nFull data:")
for row in backend.execute("SELECT name, score FROM page_demo ORDER BY score DESC", options=DQL).data:
    print(f"  {row['name']}: score={row['score']}")

print("\n[1] ROWNUM (traditional Oracle)")
result = backend.execute(
    "SELECT name, score FROM (SELECT name, score FROM page_demo ORDER BY id) "
    "WHERE ROWNUM <= 5",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}: score={row['score']}")

print("\n[2] FETCH FIRST 3 ROWS ONLY (top-N)")
result = backend.execute(
    "SELECT name, score FROM page_demo ORDER BY score DESC FETCH FIRST 3 ROWS ONLY",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}: score={row['score']}")

print("\n[3] OFFSET 3 ROWS FETCH NEXT 3 ROWS ONLY (page 2)")
result = backend.execute(
    "SELECT name, score FROM page_demo ORDER BY score DESC "
    "OFFSET 3 ROWS FETCH NEXT 3 ROWS ONLY",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}: score={row['score']}")

print("\n[4] FETCH FIRST 20 PERCENT ROWS ONLY")
result = backend.execute(
    "SELECT name, score FROM page_demo ORDER BY score DESC "
    "FETCH FIRST 20 PERCENT ROWS ONLY",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}: score={row['score']}")

print("\n[5] WITH TIES (include tie-breaks)")
backend.execute(
    "UPDATE page_demo SET score = 80 WHERE name = :1", ("Diana",),
    options=ExecutionOptions(stmt_type=StatementType.UPDATE),
)
backend.execute(
    "UPDATE page_demo SET score = 80 WHERE name = :1", ("Eve",),
    options=ExecutionOptions(stmt_type=StatementType.UPDATE),
)
result = backend.execute(
    "SELECT name, score FROM page_demo ORDER BY score DESC "
    "FETCH FIRST 5 ROWS WITH TIES",
    options=DQL,
)
for row in result.data:
    print(f"  {row['name']}: score={row['score']}")

backend.execute("DROP TABLE page_demo PURGE", options=DDL)
backend.disconnect()
print("\nPagination examples completed successfully.")