"""
Oracle PIVOT / UNPIVOT.

PIVOT rotates rows into columns (cross-tabulation). UNPIVOT does the reverse.
Oracle has a dedicated PIVOT/UNPIVOT keyword extension that is more concise
than the CASE-expression approach used by most other databases.

This example demonstrates:
1. PIVOT — rotating category values into columns
2. PIVOT with multiple aggregate columns
3. PIVOT XML (keyword returning XML-typed result)
4. UNPIVOT — rotating columns back to rows
5. UNPIVOT with NULL handling (INCLUDE NULLS / EXCLUDE NULLS)

Oracle Version Support: PIVOT/UNPIVOT 11g+ (XML PIVOT: 11g+)
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE pivot_sales (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        year NUMBER(4) NOT NULL,
        quarter VARCHAR2(10) NOT NULL,
        amount NUMBER(10, 2) NOT NULL
    )
""", options=DDL)

for y, q, a in [
    (2024, "Q1", 10000), (2024, "Q2", 12000), (2024, "Q3", 15000), (2024, "Q4", 11000),
    (2025, "Q1", 13000), (2025, "Q2", 14000), (2025, "Q3", 16000), (2025, "Q4", 12000),
]:
    backend.execute(
        "INSERT INTO pivot_sales (year, quarter, amount) VALUES (:1, :2, :3)",
        (y, q, a), options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )

print("=" * 60)
print("Oracle PIVOT / UNPIVOT Examples")
print("=" * 60)

print("\n[1] Raw data")
for row in backend.execute("SELECT * FROM pivot_sales ORDER BY year, quarter", options=DQL).data:
    print(f"  {row['year']} {row['quarter']}: ${row['amount']}")

print("\n[2] PIVOT: quarters as columns")
result = backend.execute(
    "SELECT * FROM pivot_sales PIVOT (SUM(amount) FOR quarter IN "
    "('Q1' AS q1, 'Q2' AS q2, 'Q3' AS q3, 'Q4' AS q4)) ORDER BY year",
    options=DQL,
)
for row in result.data:
    print(f"  {row['year']}: Q1={row['q1']}, Q2={row['q2']}, Q3={row['q3']}, Q4={row['q4']}")

print("\n[3] PIVOT XML (11g+) — produce XML output")
result = backend.execute(
    "SELECT * FROM pivot_sales PIVOT XML (SUM(amount) FOR quarter IN "
    "(SELECT DISTINCT quarter FROM pivot_sales)) ORDER BY year",
    options=DQL,
)
for row in result.data:
    print(f"  year={row['year']}: ...")

print("\n[4] UNPIVOT — columns back to rows")
backend.execute("""
    CREATE TABLE unpivot_demo (
        year NUMBER(4) PRIMARY KEY,
        q1 NUMBER(10, 2),
        q2 NUMBER(10, 2),
        q3 NUMBER(10, 2),
        q4 NUMBER(10, 2)
    )
""", options=DDL)
backend.execute(
    "INSERT INTO unpivot_demo (year, q1, q2, q3, q4) VALUES (:1, :2, :3, :4, :5)",
    (2025, 100, 200, 300, 400), options=ExecutionOptions(stmt_type=StatementType.INSERT),
)

result = backend.execute(
    "SELECT year, quarter, amount FROM unpivot_demo "
    "UNPIVOT (amount FOR quarter IN (q1 AS 'Q1', q2 AS 'Q2', q3 AS 'Q3', q4 AS 'Q4'))",
    options=DQL,
)
print("UNPIVOT result:")
for row in result.data:
    print(f"  {row['year']} {row['quarter']}: ${row['amount']}")

backend.execute("DROP TABLE unpivot_demo PURGE", options=DDL)
backend.execute("DROP TABLE pivot_sales PURGE", options=DDL)
backend.disconnect()
print("\nPIVOT/UNPIVOT examples completed successfully.")