# tests/rhosocial/activerecord_oracle_test/feature/backend/ddl/test_default_model_ddl.py
"""Default-type model rendering — Oracle.

``DefaultUser`` declares plain Python types with no ``UseSqlType``; Oracle
derives the column types via its own suggestion mapping. A concrete server
version is supplied so the dialect renders offline.
"""

from rhosocial.activerecord.backend.impl.oracle.dialect import OracleDialect
from rhosocial.activerecord.examples.ddl_default_types import DefaultUser


def _render() -> str:
    dialect = OracleDialect(version=(23, 0, 0))
    sql, _ = DefaultUser.generate_create_table(dialect=dialect).to_sql()
    return sql


def test_default_user_has_no_explicit_sql_types():
    assert DefaultUser.__table_field_sql_types__ == {}


def test_oracle_default_user_ddl_columns():
    sql = _render()
    assert "CREATE TABLE DEFAULT_USERS" in sql
    assert "ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql
    assert "USERNAME VARCHAR2(255) NOT NULL" in sql
    assert "EMAIL VARCHAR2(255) NOT NULL" in sql
    assert "IS_ACTIVE NUMBER(1) NOT NULL" in sql
    assert "BALANCE FLOAT(126) NOT NULL" in sql
    assert "CREATED_AT TIMESTAMP NOT NULL" in sql
    assert "METADATA VARCHAR2(4000) NOT NULL" in sql
    assert "AVATAR BLOB NOT NULL" in sql
    assert "BIRTHDAY DATE" in sql