# tests/rhosocial/activerecord_oracle_test/feature/backend/ddl/test_typed_model_ddl.py
"""Cross-backend UseSqlType demonstration — Oracle rendering.

The shared ``TypedUser`` model (core generic types) renders Oracle-native SQL
without any per-dialect string mappings. A concrete server version is supplied
so the dialect renders offline (no DB connection needed).
"""

from rhosocial.activerecord.backend.impl.oracle.dialect import OracleDialect
from rhosocial.activerecord.examples.ddl_types import TypedUser


def _render() -> str:
    dialect = OracleDialect(version=(23, 0, 0))
    sql, _ = TypedUser.generate_create_table(dialect=dialect).to_sql()
    return sql


def test_oracle_typed_user_ddl_columns():
    sql = _render()
    assert "CREATE TABLE TYPED_USERS" in sql
    assert "ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql
    assert "USERNAME VARCHAR2(100) NOT NULL" in sql
    assert "EMAIL VARCHAR2(255) NOT NULL" in sql
    assert "IS_ACTIVE NUMBER(1) NOT NULL" in sql
    assert "BALANCE NUMBER(10, 2)" in sql
    assert "BIRTHDAY DATE" in sql
    assert "CREATED_AT TIMESTAMP NOT NULL" in sql
    assert "BIO CLOB" in sql
    assert "METADATA VARCHAR2(4000)" in sql
    assert "BIG_COUNTER NUMBER(19)" in sql
    assert "AVATAR BLOB" in sql
    assert "WAKE_UP_TIME VARCHAR2(8)" in sql


def test_oracle_typed_user_no_per_dialect_string_keys():
    for _field_name, marker in TypedUser.__table_field_sql_types__.items():
        assert not hasattr(marker, "dialect_types")
        assert marker.data_type is not None