"""
INSERT Statements — single, batch, expression-based.

This example demonstrates:
1. Raw INSERT (inline SQL with positional placeholders :1, :2)
2. Expression-based INSERT (InsertExpression, ValuesSource) — using Django-style SQL output
3. Batch INSERT
4. Verifying inserted rows

Oracle Version Support: 12c+
"""

import os

import re

from rhosocial.activerecord.backend.expression import InsertExpression, ValuesSource, TableExpression
from rhosocial.activerecord.backend.expression.core import Literal
from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()
dialect = backend.dialect

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

# Pre-cleanup so the example is idempotent
try:
    backend.execute("DROP TABLE eg_insert_demo PURGE", options=DDL)
except Exception:
    pass

backend.execute("""
    CREATE TABLE eg_insert_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        score NUMBER(3) DEFAULT 0,
        status VARCHAR2(20) DEFAULT 'pending'
    )
""", options=DDL)

print("=" * 60)
print("INSERT Examples")
print("=" * 60)

# --- 1. Raw INSERT via inline SQL ---
print("\n[1] Raw INSERT (inline SQL with :1/:2/:3 placeholders)")
backend.execute(
    "INSERT INTO eg_insert_demo (name, score, status) VALUES (:1, :2, :3)",
    ("Alice", 85, "active"),
    options=ExecutionOptions(stmt_type=StatementType.INSERT),
)
print("  Inserted 'Alice' (score=85, active)")

# --- 2. Expression-based INSERT (generate + use raw SQL) ---
print("\n[2] Expression-based INSERT (build with InsertExpression, generate SQL)")
vals = ValuesSource(
    dialect,
    [[Literal(dialect, "Bob"), Literal(dialect, 92), Literal(dialect, "active")]],
)
target = TableExpression(dialect, "eg_insert_demo")
insert_expr = InsertExpression(
    dialect=dialect,
    into=target,
    source=vals,
    columns=["name", "score", "status"],
)
gen_sql, gen_params = insert_expr.to_sql()
print(f"  Generated SQL: {gen_sql}")
print(f"  Generated params: {gen_params}")
backend.execute(gen_sql, gen_params, options=ExecutionOptions(stmt_type=StatementType.INSERT))
print("  Inserted 'Bob' (score=92, active)")

# --- 3. Batch INSERT ---
print("\n[3] Batch INSERT (multiple single INSERTs)")
batch = [
    ("Charlie", 78, "active"),
    ("Diana", 65, "inactive"),
    ("Eve", 95, "active"),
]
for n_, s, st in batch:
    backend.execute(
        "INSERT INTO eg_insert_demo (name, score, status) VALUES (:1, :2, :3)",
        (n_, s, st),
        options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )
print(f"  Batch-inserted {len(batch)} rows")

# --- Verify ---
result = backend.execute("SELECT * FROM eg_insert_demo ORDER BY id", options=DQL)
print(f"\nAll rows ({len(result.data)}):")
for row in result.data:
    print(f"  ID={row['id']}, name={row['name']}, score={row['score']}, status={row['status']}")

try:
    backend.execute("DROP TABLE eg_insert_demo PURGE", options=DDL)
except Exception:
    pass
backend.disconnect()
print("\nInsert examples completed successfully.")