"""
MERGE-based Upsert (Oracle-style).

Oracle does not have the ON CONFLICT DO UPDATE clause (PostgreSQL/MySQL
INSERT ... ON DUPLICATE KEY). Instead, Oracle uses the MERGE INTO ...
USING ... ON ... WHEN MATCHED THEN UPDATE ... WHEN NOT MATCHED THEN INSERT
syntax since Oracle 10g.

This example demonstrates:
1. Preparing source data via a VALUES source or inline table
2. Executing a MERGE statement for upsert behavior
3. Verifying result

Oracle Version Support: 12c+ (MERGE available since 10g)
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE merge_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        sku VARCHAR2(50) NOT NULL UNIQUE,
        stock NUMBER(10) DEFAULT 0,
        price NUMBER(10, 2)
    )
""", options=DDL)

backend.execute(
    "INSERT INTO merge_demo (sku, stock, price) VALUES (:1, :2, :3)",
    ("ITEM-A", 10, 19.99),
    options=ExecutionOptions(stmt_type=StatementType.INSERT),
)
backend.execute(
    "INSERT INTO merge_demo (sku, stock, price) VALUES (:1, :2, :3)",
    ("ITEM-B", 5, 29.99),
    options=ExecutionOptions(stmt_type=StatementType.INSERT),
)

print("=" * 60)
print("MERGE / Upsert Examples (Oracle MERGE INTO ...)")
print("=" * 60)

print("\nBefore MERGE:")
result = backend.execute("SELECT sku, stock, price FROM merge_demo ORDER BY sku", options=DQL)
for row in result.data:
    print(f"  {row['sku']}: stock={row['stock']}, price={row['price']}")

print("\n[1] MERGE — INSERT new row, UPDATE existing row")
backend.execute("""
    MERGE INTO merge_demo d
    USING (
        SELECT 'ITEM-A' AS sku, 20 AS stock, 24.99 AS price FROM DUAL
        UNION ALL
        SELECT 'ITEM-C', 15, 9.99 FROM DUAL
    ) s
    ON (d.sku = s.sku)
    WHEN MATCHED THEN
        UPDATE SET d.stock = d.stock + s.stock, d.price = s.price
    WHEN NOT MATCHED THEN
        INSERT (sku, stock, price) VALUES (s.sku, s.stock, s.price)
""", options=ExecutionOptions(stmt_type=StatementType.DML))

print("\nAfter MERGE:")
result = backend.execute("SELECT sku, stock, price FROM merge_demo ORDER BY sku", options=DQL)
for row in result.data:
    print(f"  {row['sku']}: stock={row['stock']}, price={row['price']}")

backend.execute("DROP TABLE merge_demo PURGE", options=DDL)
backend.disconnect()
print("\nMERGE upsert example completed successfully.")