"""
DELETE Statements.

This example demonstrates:
1. Simple DELETE by condition
2. DELETE all rows
3. Verify row counts

Oracle Version Support: 12c+
"""

import os

from rhosocial.activerecord.backend.impl.oracle import OracleBackend, OracleConnectionConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

config = OracleConnectionConfig(
    host=os.getenv('ORACLE_HOST', '127.0.0.1'),
    port=int(os.getenv('ORACLE_PORT', '11522')),
    username=os.getenv('ORACLE_USER', 'system'),
    password=os.getenv('ORACLE_PASSWORD', 'Password1!'),
    service_name=os.getenv('ORACLE_SERVICE', 'xepdb1'),
)

backend = OracleBackend(connection_config=config)
backend.connect()

DDL = ExecutionOptions(stmt_type=StatementType.DDL)
DQL = ExecutionOptions(stmt_type=StatementType.DQL)

backend.execute("""
    CREATE TABLE delete_demo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        status VARCHAR2(20) DEFAULT 'active'
    )
""", options=DDL)

for n, st in [("Alpha", "active"), ("Bravo", "inactive"), ("Charlie", "active"),
              ("Delta", "inactive")]:
    backend.execute(
        "INSERT INTO delete_demo (name, status) VALUES (:1, :2)",
        (n, st),
        options=ExecutionOptions(stmt_type=StatementType.INSERT),
    )

print("=" * 60)
print("DELETE Examples")
print("=" * 60)

print("\nBefore DELETE:")
for row in backend.execute("SELECT * FROM delete_demo ORDER BY id", options=DQL).data:
    print(f"  {row['id']}: {row['name']} ({row['status']})")

# --- 1. DELETE by condition ---
print("\n[1] DELETE inactive rows")
backend.execute(
    "DELETE FROM delete_demo WHERE status = :1",
    ("inactive",),
    options=ExecutionOptions(stmt_type=StatementType.DELETE),
)

print("\nAfter deleting inactive rows:")
for row in backend.execute("SELECT * FROM delete_demo ORDER BY id", options=DQL).data:
    print(f"  {row['id']}: {row['name']} ({row['status']})")

# --- 2. DELETE all ---
print("\n[2] DELETE all remaining rows")
backend.execute(
    "DELETE FROM delete_demo",
    options=ExecutionOptions(stmt_type=StatementType.DELETE),
)

count = len(backend.execute("SELECT * FROM delete_demo", options=DQL).data)
print(f"Remaining rows: {count}")

backend.execute("DROP TABLE delete_demo PURGE", options=DDL)
backend.disconnect()
print("\nDelete examples completed successfully.")