# tests/rhosocial/activerecord_oracle_test/feature/query/test_collation_expression.py
"""
Tests for expression-level COLLATE support on Oracle.
"""

import pytest

from rhosocial.activerecord.backend.expression import Column, Literal
from rhosocial.activerecord.backend.expression.collation import CollationName
from rhosocial.activerecord.backend.impl.oracle import OracleCollation, OracleDialect


@pytest.fixture
def dialect():
    return OracleDialect(version=(19, 0, 0))


@pytest.fixture
def collation_table(oracle_backend):
    oracle_backend.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE test_collation_expression';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN
                    RAISE;
                END IF;
        END;
    """)
    oracle_backend.execute("""
        CREATE TABLE test_collation_expression (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(100) NOT NULL
        )
    """)
    oracle_backend.execute("""
        INSERT INTO test_collation_expression (name)
        VALUES ('Alice')
    """)
    oracle_backend.execute("""
        INSERT INTO test_collation_expression (name)
        VALUES ('alice')
    """)
    oracle_backend.execute("""
        INSERT INTO test_collation_expression (name)
        VALUES ('Bob')
    """)
    yield "test_collation_expression"
    oracle_backend.execute("DROP TABLE test_collation_expression")


class TestOracleCollationExpression:
    def test_column_collate_generates_sql(self, dialect):
        expr = Column(dialect, "name", table="users").collate(OracleCollation.BINARY_CI)

        sql, params = expr.to_sql()

        assert sql == 'USERS.name COLLATE BINARY_CI'
        assert params == ()

    def test_literal_collate_preserves_parameter_binding(self, dialect):
        expr = Literal(dialect, "Alice").collate(OracleCollation.BINARY_CI)

        sql, params = expr.to_sql()

        assert sql == "? COLLATE BINARY_CI"
        assert params == ("Alice",)

    def test_rejects_collate_on_older_version(self):
        dialect = OracleDialect(version=(12, 1, 0))
        expr = Column(dialect, "name").collate(OracleCollation.BINARY_CI)

        with pytest.raises(Exception, match="COLLATE expression"):
            expr.to_sql()

    def test_rejects_schema_qualified_collation(self, dialect):
        expr = Column(dialect, "name").collate(CollationName("BINARY_CI", schema="SYS"))

        with pytest.raises(Exception, match="schema-qualified or keyword COLLATE"):
            expr.to_sql()

    def test_rejects_unsupported_collation(self, dialect):
        expr = Column(dialect, "name").collate("unknown_ci")

        with pytest.raises(ValueError, match="Unsupported Oracle collation"):
            expr.to_sql()

    @pytest.mark.skip(reason="Oracle feature/query tests do not expose a raw backend fixture")
    def test_collate_executes_case_sensitive_match(self, oracle_backend, collation_table):
        if oracle_backend.dialect.get_server_version() < (12, 2, 0):
            pytest.skip("Oracle expression-level COLLATE requires Oracle 12.2+")
        expr = Column(oracle_backend.dialect, "name", table=collation_table).collate(
            OracleCollation.BINARY
        )
        sql, params = expr.to_sql()

        rows = oracle_backend.fetch_all(
            f"SELECT name FROM {collation_table} WHERE {sql} = ? ORDER BY id",
            (*params, "Alice"),
        )

        assert [row["name"] for row in rows] == ["Alice"]

    @pytest.mark.skip(reason="Oracle feature/query tests do not expose a raw backend fixture")
    def test_collate_executes_case_insensitive_match(self, oracle_backend, collation_table):
        if oracle_backend.dialect.get_server_version() < (12, 2, 0):
            pytest.skip("Oracle expression-level COLLATE requires Oracle 12.2+")
        expr = Column(oracle_backend.dialect, "name", table=collation_table).collate(
            OracleCollation.BINARY_CI
        )
        sql, params = expr.to_sql()

        rows = oracle_backend.fetch_all(
            f"SELECT name FROM {collation_table} WHERE {sql} = ? ORDER BY id",
            (*params, "Alice"),
        )

        assert [row["name"] for row in rows] == ["Alice", "alice"]
