"""
Schema diff: detect added tables.

Builds a ``SchemaSnapshot`` before and after creating a table, then uses
``OracleSchemaDiffer`` to report the change.

Oracle notes:
- Identifiers are upper-cased by the dialect (unquoted identifiers).
- Auto-increment uses ``GENERATED BY DEFAULT AS IDENTITY`` (Oracle 12c+).

Supported versions: Oracle 12c+
"""

# ============================================================
# SECTION: Setup (necessary for execution, reference only)
# ============================================================
import os
from rhosocial.activerecord.backend.impl.oracle import OracleBackend
from rhosocial.activerecord.backend.impl.oracle.config import OracleConnectionConfig

config = OracleConnectionConfig(
    host=os.getenv("ORACLE_HOST", "localhost"),
    port=int(os.getenv("ORACLE_PORT", "1521")),
    username=os.getenv("ORACLE_USER", "system"),
    password=os.getenv("ORACLE_PASSWORD", ""),
    service_name=os.getenv("ORACLE_SERVICE", "XEPDB1"),
)
backend = OracleBackend(connection_config=config)
backend.connect()
backend.introspect_and_adapt()
dialect = backend.dialect

# Clean up any leftover tables
from rhosocial.activerecord.backend.expression import (  # noqa: E402
    DropTableExpression,
)
expr = DropTableExpression(dialect, "USERS", if_exists=True)
sql, params = expr.to_sql()
backend.execute(sql, params)

# ============================================================
# SECTION: Business Logic (the pattern to learn)
# ============================================================
from rhosocial.activerecord.backend.schema import (  # noqa: E402
    SyncSchemaSnapshotBuilder,
)
from rhosocial.activerecord.backend.impl.oracle.schema.differ import (  # noqa: E402
    OracleSchemaDiffer,
)
from rhosocial.activerecord.backend.expression import (  # noqa: E402
    CreateTableExpression, ColumnDefinition,
    ColumnConstraint, ColumnConstraintType,
)
from rhosocial.activerecord.backend.expression.types import (  # noqa: E402
    IntegerType, VarCharType,
)

builder = SyncSchemaSnapshotBuilder(backend.introspector, dialect)
snapshot_before = builder.build()

# Create a new table. Oracle 12c+ supports GENERATED AS IDENTITY for the
# primary key column.
expr = CreateTableExpression(
    dialect=dialect, table="USERS", columns=[
        ColumnDefinition("ID", IntegerType(),
            constraints=[
                ColumnConstraint(constraint_type=ColumnConstraintType.PRIMARY_KEY, is_auto_increment=True),
            ]),
        ColumnDefinition("NAME", VarCharType(100)),
    ]
)
sql, params = expr.to_sql()
backend.execute(sql, params)

snapshot_after = builder.build()

differ = OracleSchemaDiffer()
diff = differ.compare(snapshot_before, snapshot_after)

# ============================================================
# SECTION: Execution (run the expression)
# ============================================================
print(f"Added tables:    {diff.added_tables}")
print(f"Removed tables:  {diff.removed_tables}")
print(f"Modified tables: {diff.modified_tables}")
print(f"Diff is empty:   {diff.is_empty}")

# ============================================================
# SECTION: Teardown (necessary for execution, reference only)
# ============================================================
expr = DropTableExpression(dialect, "USERS", if_exists=True)
sql, params = expr.to_sql()
backend.execute(sql, params)
backend.disconnect()
