# tests/providers/basic_connection.py
"""
Concrete implementation of IBasicConnectionProvider for Oracle backend.

This provider sets up connection pools and models for testing
ActiveRecord context awareness.
"""

from typing import Type, Tuple, Optional, List

from rhosocial.activerecord.model import ActiveRecord, AsyncActiveRecord
from rhosocial.activerecord.backend.impl.oracle import OracleBackend
from rhosocial.activerecord.backend.impl.oracle.async_backend import AsyncOracleBackend
from rhosocial.activerecord.connection.pool import BackendPool, AsyncBackendPool, PoolConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

from rhosocial.activerecord.testsuite.feature.basic.connection.interfaces import IBasicConnectionProvider
from .scenarios import get_scenario, get_enabled_scenarios


# Oracle 12c+ uses GENERATED BY DEFAULT AS IDENTITY in place of AUTO_INCREMENT.
# DROP TABLE ... IF EXISTS is not valid Oracle SQL; wrap drops in a PL/SQL
# anonymous block that silently ignores missing tables.
_DROP_TABLE_BLOCK = (
    "BEGIN EXECUTE IMMEDIATE 'DROP TABLE test_users CASCADE CONSTRAINTS'; "
    "EXCEPTION WHEN OTHERS THEN NULL; END;"
)
_CREATE_TABLE_SQL = """
    CREATE TABLE test_users (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL,
        email VARCHAR2(255) NOT NULL
    )
"""


class SyncTestUser(ActiveRecord):
    """Sync test user model for connection pool tests."""

    __table_name__ = "test_users"
    id: Optional[int] = None
    name: str
    email: str


class AsyncTestUser(AsyncActiveRecord):
    """Async test user model for connection pool tests."""

    __table_name__ = "test_users"
    id: Optional[int] = None
    name: str
    email: str


class BasicConnectionProvider(IBasicConnectionProvider):
    """Oracle backend implementation for basic connection pool context tests."""

    def __init__(self):
        self._active_backends: List = []
        self._active_async_backends: List = []

    def get_test_scenarios(self) -> list:
        """Returns available test scenarios."""
        return list(get_enabled_scenarios().keys())

    def _create_test_table(self, backend):
        """Create the test_users table."""
        try:
            # Oracle thin driver rejects anonymous-PL/SQL blocks via
            # cursor.execute(); delegates to executescript which splits on
            # ``;`` and runs each statement individually.
            backend.executescript(_DROP_TABLE_BLOCK)
        except Exception:
            pass

        backend.executescript(_CREATE_TABLE_SQL)

    async def _create_test_table_async(self, backend):
        """Create the test_users table asynchronously."""
        try:
            # Oracle thin driver rejects anonymous-PL/SQL blocks via
            # cursor.execute(); delegates to executescript which splits on
            # ``;`` and runs each statement individually.
            await backend.executescript(_DROP_TABLE_BLOCK)
        except Exception:
            pass

        await backend.executescript(_CREATE_TABLE_SQL)

    def setup_sync_pool_and_model(self, scenario_name: str) -> Tuple[BackendPool, Type[ActiveRecord]]:
        """Setup sync connection pool and model for context tests."""
        import logging as _logging
        _log = _logging.getLogger("rhosocial.activerecord.testsuite.oracle.debug.pool")
        _, config = get_scenario(scenario_name)
        _log.error("DEBUG_SETUP_SYNC_POOL_AND_MODEL_ENTRY scenario=%s", scenario_name)

        pool_config = PoolConfig(
            min_size=1, max_size=5,
            backend_factory=lambda: OracleBackend(connection_config=config),
        )
        pool = BackendPool.create(pool_config)
        _log.error("DEBUG_POOL_TYPE=%s", type(pool).__name__)

        with pool.connection() as backend:
            self._create_test_table(backend)
            self._active_backends.append(backend)
            _log.error("DEBUG_BACKEND_TYPE=%s TMGR=%s", type(backend).__name__, type(backend.transaction_manager).__name__ if hasattr(backend, '_transaction_manager') else None)

        # Configure model against a separate backend so that
        # model.backend() returning the pool's context backend is exercised.
        SyncTestUser.configure(config, OracleBackend)
        self._active_backends.append(SyncTestUser.__backend__)

        # Defensive: pytest-asyncio 1.4.0 in auto mode has been observed to
        # leave ``AsyncTestUser.__backend__`` populated with an AsyncOracleBackend
        # from a previous async test in the same module (which imports both
        # sync and async tests). Forcing it to ``None`` guarantees that any
        # later fixture cleanup that touches the async model cannot influence
        # the synchronous transaction fixture.
        AsyncTestUser.__backend__ = None
        _log.error("DEBUG_RETURN pool=%s", type(pool).__name__)
        return pool, SyncTestUser

    async def setup_async_pool_and_model(self, scenario_name: str) -> Tuple[AsyncBackendPool, Type[AsyncActiveRecord]]:
        """Setup async connection pool and model for context tests."""
        _, config = get_scenario(scenario_name)

        pool_config = PoolConfig(
            min_size=1, max_size=5,
            backend_factory=lambda: AsyncOracleBackend(connection_config=config),
        )
        pool = await AsyncBackendPool.create(pool_config)

        async with pool.connection() as backend:
            await self._create_test_table_async(backend)
            self._active_async_backends.append(backend)

        await AsyncTestUser.configure(config, AsyncOracleBackend)
        self._active_async_backends.append(AsyncTestUser.__backend__)

        return pool, AsyncTestUser

    def cleanup_sync(self, scenario_name: str, pool: BackendPool):
        """Cleanup after sync tests."""
        try:
            pool.close(timeout=1.0, force=True)
        except Exception:
            pass

        for backend in self._active_backends:
            try:
                backend.disconnect()
            except Exception:
                pass
        self._active_backends.clear()

    async def cleanup_async(self, scenario_name: str, pool: AsyncBackendPool):
        """Cleanup after async tests."""
        try:
            await pool.close(timeout=1.0, force=True)
        except Exception:
            pass

        for backend in self._active_async_backends:
            try:
                await backend.disconnect()
            except Exception:
                pass
        self._active_async_backends.clear()

    def setup_sync_pool_for_crud(self, scenario_name: str) -> Tuple[BackendPool, Type[ActiveRecord]]:
        """Setup sync connection pool for CRUD tests."""
        return self.setup_sync_pool_and_model(scenario_name)

    async def setup_async_pool_for_crud(self, scenario_name: str) -> Tuple[AsyncBackendPool, Type[AsyncActiveRecord]]:
        """Setup async connection pool for CRUD tests."""
        return await self.setup_async_pool_and_model(scenario_name)
