# tests/providers/query_connection.py
"""
Concrete implementation of IQueryConnectionProvider for Oracle backend.

This provider sets up connection pools and models for testing
query classes context awareness (ActiveQuery, CTEQuery, SetOperationQuery).
"""

from typing import Type, Tuple, Optional, List

from rhosocial.activerecord.model import ActiveRecord, AsyncActiveRecord
from rhosocial.activerecord.backend.impl.oracle import OracleBackend
from rhosocial.activerecord.backend.impl.oracle.async_backend import AsyncOracleBackend
from rhosocial.activerecord.connection.pool import BackendPool, AsyncBackendPool, PoolConfig
from rhosocial.activerecord.backend.options import ExecutionOptions
from rhosocial.activerecord.backend.schema import StatementType

from rhosocial.activerecord.testsuite.feature.query.connection.interfaces import IQueryConnectionProvider
from .scenarios import get_scenario, get_enabled_scenarios


_DROP_TABLE_BLOCK = (
    "BEGIN EXECUTE IMMEDIATE 'DROP TABLE test_users CASCADE CONSTRAINTS'; "
    "EXCEPTION WHEN OTHERS THEN NULL; END;"
)
_CREATE_TABLE_SQL = """
    CREATE TABLE test_users (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL,
        email VARCHAR2(255) NOT NULL
    )
"""


class SyncQueryTestUser(ActiveRecord):
    """Sync test user model for query connection pool tests."""

    __table_name__ = "test_users"
    id: Optional[int] = None
    name: str
    email: str


class AsyncQueryTestUser(AsyncActiveRecord):
    """Async test user model for query connection pool tests."""

    __table_name__ = "test_users"
    id: Optional[int] = None
    name: str
    email: str


class QueryConnectionProvider(IQueryConnectionProvider):
    """Oracle backend implementation for query connection pool context tests."""

    def __init__(self):
        self._active_backends: List = []
        self._active_async_backends: List = []

    def get_test_scenarios(self) -> list:
        """Returns available test scenarios."""
        return list(get_enabled_scenarios().keys())

    def _create_test_table(self, backend):
        """Create the test_users table."""
        try:
            backend.execute(
                _DROP_TABLE_BLOCK,
                options=ExecutionOptions(stmt_type=StatementType.DDL),
            )
        except Exception:
            pass

        backend.execute(
            _CREATE_TABLE_SQL,
            options=ExecutionOptions(stmt_type=StatementType.DDL),
        )

    async def _create_test_table_async(self, backend):
        """Create the test_users table asynchronously."""
        try:
            await backend.execute(
                _DROP_TABLE_BLOCK,
                options=ExecutionOptions(stmt_type=StatementType.DDL),
            )
        except Exception:
            pass

        await backend.execute(
            _CREATE_TABLE_SQL,
            options=ExecutionOptions(stmt_type=StatementType.DDL),
        )

    def setup_sync_pool_and_model(self, scenario_name: str) -> Tuple[BackendPool, Type[ActiveRecord]]:
        """Setup sync connection pool and model for query context tests."""
        _, config = get_scenario(scenario_name)

        pool_config = PoolConfig(
            min_size=1, max_size=5,
            backend_factory=lambda: OracleBackend(connection_config=config),
        )
        pool = BackendPool.create(pool_config)

        with pool.connection() as backend:
            self._create_test_table(backend)
            self._active_backends.append(backend)

        SyncQueryTestUser.configure(config, OracleBackend)
        self._active_backends.append(SyncQueryTestUser.__backend__)

        return pool, SyncQueryTestUser

    async def setup_async_pool_and_model(self, scenario_name: str) -> Tuple[AsyncBackendPool, Type[AsyncActiveRecord]]:
        """Setup async connection pool and model for query context tests."""
        _, config = get_scenario(scenario_name)

        pool_config = PoolConfig(
            min_size=1, max_size=5,
            backend_factory=lambda: AsyncOracleBackend(connection_config=config),
        )
        pool = await AsyncBackendPool.create(pool_config)

        async with pool.connection() as backend:
            await self._create_test_table_async(backend)
            self._active_async_backends.append(backend)

        await AsyncQueryTestUser.configure(config, AsyncOracleBackend)
        self._active_async_backends.append(AsyncQueryTestUser.__backend__)

        return pool, AsyncQueryTestUser

    def cleanup_sync(self, scenario_name: str, pool: BackendPool):
        """Cleanup after sync tests."""
        pool.close(timeout=1.0)

        for backend in self._active_backends:
            try:
                backend.disconnect()
            except Exception:
                pass
        self._active_backends.clear()

    async def cleanup_async(self, scenario_name: str, pool: AsyncBackendPool):
        """Cleanup after async tests."""
        await pool.close(timeout=1.0)

        for backend in self._active_async_backends:
            try:
                await backend.disconnect()
            except Exception:
                pass
        self._active_async_backends.clear()
