# tests/providers/relation.py
"""
Concrete implementations of `IRelationSyncProvider` and
`IRelationAsyncProvider` for the Oracle backend.
"""

import logging
from typing import Dict, List, Tuple, Type, Set

from rhosocial.activerecord.model import ActiveRecord, AsyncActiveRecord  # noqa: E402
from rhosocial.activerecord.backend.options import ExecutionOptions, StatementType  # noqa: E402
from rhosocial.activerecord.testsuite.feature.relation.interfaces import (  # noqa: E402
    IRelationSyncProvider,
    IRelationAsyncProvider,
)
from rhosocial.activerecord.testsuite.feature.relation.fixtures.models import (  # noqa: E402
    Employee,
    Department,
    Author,
    Book,
    Chapter,
    Profile,
    User,
    Post,
    Comment,
    AsyncUser,
    AsyncPost,
    AsyncComment,
    BoundaryOwner,
    BoundaryProfile,
    BoundaryPost,
    AsyncBoundaryOwner,
    AsyncBoundaryProfile,
    AsyncBoundaryPost,
)

from .scenarios import get_enabled_scenarios, get_scenario  # noqa: E402

logger = logging.getLogger(__name__)


EMPLOYEE_DEPARTMENT_SCHEMA = """
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE employees CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE departments CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    CREATE TABLE departments (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL,
        description CLOB
    );
    CREATE TABLE employees (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR2(255) NOT NULL,
        department_id NUMBER(10) NOT NULL
    );
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM employees'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM departments'; EXCEPTION WHEN OTHERS THEN NULL; END;
"""

AUTHOR_BOOK_SCHEMA = """
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE chapters CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE books CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE profiles CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE authors CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    CREATE TABLE authors (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL
    );
    CREATE TABLE books (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(255) NOT NULL,
        author_id NUMBER(10) NOT NULL
    );
    CREATE TABLE chapters (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(255) NOT NULL,
        book_id NUMBER(10) NOT NULL
    );
    CREATE TABLE profiles (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bio CLOB NOT NULL,
        author_id NUMBER(10) NOT NULL
    );
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM chapters'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM books'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM profiles'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM authors'; EXCEPTION WHEN OTHERS THEN NULL; END;
"""

USER_POST_COMMENT_SCHEMA = """
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE comments CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE posts CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
    CREATE TABLE users (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL,
        email VARCHAR2(255),
        settings CLOB
    );
    CREATE TABLE posts (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(255) NOT NULL,
        body CLOB NOT NULL,
        user_id NUMBER(10) NOT NULL,
        view_count NUMBER(10) DEFAULT 0 NOT NULL,
        metadata CLOB
    );
    CREATE TABLE comments (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        body CLOB NOT NULL,
        post_id NUMBER(10) NOT NULL,
        meta CLOB
    );
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM comments'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM posts'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM users'; EXCEPTION WHEN OTHERS THEN NULL; END;
"""

RELATION_BOUNDARY_SCHEMA = """
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE relation_boundary_posts CASCADE CONSTRAINTS PURGE';
        EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE relation_boundary_profiles CASCADE CONSTRAINTS PURGE';
        EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE relation_boundary_owners CASCADE CONSTRAINTS PURGE';
        EXCEPTION WHEN OTHERS THEN NULL; END;
    CREATE TABLE relation_boundary_owners (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(255) NOT NULL
    );
    CREATE TABLE relation_boundary_profiles (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        bio CLOB NOT NULL,
        owner_id NUMBER(10) NULL
    );
    CREATE TABLE relation_boundary_posts (
        id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR2(255) NOT NULL,
        owner_id NUMBER(10) NULL
    );
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM relation_boundary_posts'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM relation_boundary_profiles'; EXCEPTION WHEN OTHERS THEN NULL; END;
    BEGIN EXECUTE IMMEDIATE 'DELETE FROM relation_boundary_owners'; EXCEPTION WHEN OTHERS THEN NULL; END;
"""


class RelationProviderBase:
    def __init__(self):
        self._scenario_db_files: Dict[str, List[str]] = {}
        self._created_tables: Set[str] = set()

    @staticmethod
    def _ddl_options() -> ExecutionOptions:
        return ExecutionOptions(stmt_type=StatementType.DDL)

    def get_test_scenarios(self) -> List[str]:
        return list(get_enabled_scenarios().keys())

    def _configure_with_shared_backend(self, model_class, config, backend_class, backend):
        model_class.__connection_config__ = config
        model_class.__backend_class__ = backend_class
        model_class.__backend__ = backend


class RelationSyncProvider(RelationProviderBase, IRelationSyncProvider):
    def __init__(self):
        super().__init__()
        self._active_backends: List = []
        self._sync_user_post_comment_setup = False
        self._sync_relation_boundary_setup = False

    def _execute_script(self, backend, sql: str):
        cursor = backend.execute(sql, options=self._ddl_options())
        return cursor

    def _setup_employee_department(self, scenario_name):
        backend_class, config = get_scenario(scenario_name)
        Employee.configure(config, backend_class)
        backend = Employee.backend()
        backend.connect()
        try:
            backend.introspect_and_adapt()
        except Exception:
            pass
        self._active_backends.append(backend)
        self._execute_script(backend, EMPLOYEE_DEPARTMENT_SCHEMA)
        self._configure_with_shared_backend(Department, config, backend_class, backend)
        self._created_tables.update(["employees", "departments"])
        return Employee, Department

    def _setup_author_book(self, scenario_name):
        backend_class, config = get_scenario(scenario_name)
        Author.configure(config, backend_class)
        backend = Author.backend()
        backend.connect()
        try:
            backend.introspect_and_adapt()
        except Exception:
            pass
        self._active_backends.append(backend)
        self._execute_script(backend, AUTHOR_BOOK_SCHEMA)
        self._configure_with_shared_backend(Book, config, backend_class, backend)
        self._configure_with_shared_backend(Chapter, config, backend_class, backend)
        self._configure_with_shared_backend(Profile, config, backend_class, backend)
        self._created_tables.update(["authors", "books", "chapters", "profiles"])
        return Author, Book, Chapter, Profile

    def _setup_user_post_comment_sync(self, scenario_name):
        if not self._sync_user_post_comment_setup:
            backend_class, config = get_scenario(scenario_name)
            User.configure(config, backend_class)
            backend = User.backend()
            backend.connect()
            try:
                backend.introspect_and_adapt()
            except Exception:
                pass
            self._active_backends.append(backend)
            self._execute_script(backend, USER_POST_COMMENT_SCHEMA)
            self._configure_with_shared_backend(Post, config, backend_class, backend)
            self._configure_with_shared_backend(Comment, config, backend_class, backend)
            self._sync_user_post_comment_setup = True
            self._created_tables.update(["users", "posts", "comments"])

    def _setup_relation_boundary_sync(self, scenario_name):
        if not self._sync_relation_boundary_setup:
            backend_class, config = get_scenario(scenario_name)
            BoundaryOwner.configure(config, backend_class)
            backend = BoundaryOwner.backend()
            backend.connect()
            try:
                backend.introspect_and_adapt()
            except Exception:
                pass
            self._active_backends.append(backend)
            self._execute_script(backend, RELATION_BOUNDARY_SCHEMA)
            self._configure_with_shared_backend(BoundaryProfile, config, backend_class, backend)
            self._configure_with_shared_backend(BoundaryPost, config, backend_class, backend)
            self._sync_relation_boundary_setup = True
            self._created_tables.update(
                ["relation_boundary_owners", "relation_boundary_profiles", "relation_boundary_posts"]
            )

    # -- IRelationSyncProvider interface --------------------------------

    def setup_employee_department_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[ActiveRecord], Type[ActiveRecord]]:
        return self._setup_employee_department(scenario_name)

    def setup_author_book_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[ActiveRecord], Type[ActiveRecord], Type[ActiveRecord], Type[ActiveRecord]]:
        return self._setup_author_book(scenario_name)

    def setup_user_model(self, scenario_name: str) -> Type[ActiveRecord]:
        self._setup_user_post_comment_sync(scenario_name)
        return User

    def setup_post_model(self, scenario_name: str) -> Type[ActiveRecord]:
        self._setup_user_post_comment_sync(scenario_name)
        return Post

    def setup_comment_model(self, scenario_name: str) -> Type[ActiveRecord]:
        self._setup_user_post_comment_sync(scenario_name)
        return Comment

    def setup_relation_boundary_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[ActiveRecord], Type[ActiveRecord], Type[ActiveRecord]]:
        self._setup_relation_boundary_sync(scenario_name)
        return BoundaryOwner, BoundaryProfile, BoundaryPost

    def load_relation_boundary_dataset(self, scenario_name: str, dataset_name: str) -> Dict[str, int]:
        self._setup_relation_boundary_sync(scenario_name)
        return self._load_relation_boundary_dataset(dataset_name)

    def _load_relation_boundary_dataset(self, dataset_name: str) -> Dict[str, int]:
        if dataset_name == "null_foreign_key":
            profile = BoundaryProfile(bio="No owner", owner_id=None)
            profile.save()
            return {"profile_id": profile.id}

        if dataset_name == "orphan_foreign_key":
            missing_owner_id = 999999
            post = BoundaryPost(title="Orphan post", owner_id=missing_owner_id)
            post.save()
            return {"post_id": post.id, "missing_owner_id": missing_owner_id}

        if dataset_name == "owner_without_children":
            owner = BoundaryOwner(name="Owner without children")
            owner.save()
            return {"owner_id": owner.id}

        if dataset_name == "multiple_has_one_matches":
            owner = BoundaryOwner(name="Owner with duplicate profiles")
            owner.save()
            first = BoundaryProfile(bio="First profile", owner_id=owner.id)
            first.save()
            second = BoundaryProfile(bio="Second profile", owner_id=owner.id)
            second.save()
            return {
                "owner_id": owner.id,
                "first_profile_id": first.id,
                "second_profile_id": second.id,
            }

        raise ValueError(f"Unknown relation boundary dataset: {dataset_name}")

    def _reset_sync_setup_state(self):
        self._sync_user_post_comment_setup = False
        self._sync_relation_boundary_setup = False

    def cleanup_after_test(self, scenario_name: str) -> None:
        for backend in self._active_backends:
            try:
                if self._created_tables:
                    for table in list(self._created_tables):
                        try:
                            backend.execute(
                                f"BEGIN EXECUTE IMMEDIATE 'DROP TABLE {table} CASCADE CONSTRAINTS PURGE'; "
                                f"EXCEPTION WHEN OTHERS THEN NULL; END;",
                                options=self._ddl_options(),
                            )
                        except Exception:
                            pass
            finally:
                try:
                    backend.disconnect()
                except Exception:
                    pass
        self._active_backends.clear()
        self._created_tables.clear()
        self._reset_sync_setup_state()


class RelationAsyncProvider(RelationProviderBase, IRelationAsyncProvider):
    def __init__(self):
        super().__init__()
        self._active_async_backends: List = []
        self._async_user_post_comment_setup = False
        self._async_relation_boundary_setup = False

    async def _execute_script_async(self, backend, sql: str):
        await backend.execute(sql, options=self._ddl_options())

    def _configure_async_model_without_connection(self, model_class, config, backend=None):
        from rhosocial.activerecord.backend.impl.oracle import AsyncOracleBackend
        if backend is None:
            backend = AsyncOracleBackend(connection_config=config)
        model_class.__connection_config__ = config
        model_class.__backend_class__ = AsyncOracleBackend
        model_class.__backend__ = backend
        return backend

    async def _setup_employee_department_async(self, scenario_name):
        _, config = get_scenario(scenario_name)
        backend = self._configure_async_model_without_connection(Employee, config)
        self._configure_async_model_without_connection(Department, config, backend)
        self._active_async_backends.append(backend)
        await backend.connect()
        try:
            await backend.introspect_and_adapt()
        except Exception:
            pass
        await self._execute_script_async(backend, EMPLOYEE_DEPARTMENT_SCHEMA)
        self._created_tables.update(["employees", "departments"])
        return Employee, Department

    async def _setup_author_book_async(self, scenario_name):
        _, config = get_scenario(scenario_name)
        backend = self._configure_async_model_without_connection(Author, config)
        self._configure_async_model_without_connection(Book, config, backend)
        self._configure_async_model_without_connection(Chapter, config, backend)
        self._configure_async_model_without_connection(Profile, config, backend)
        self._active_async_backends.append(backend)
        await backend.connect()
        try:
            await backend.introspect_and_adapt()
        except Exception:
            pass
        await self._execute_script_async(backend, AUTHOR_BOOK_SCHEMA)
        self._created_tables.update(["authors", "books", "chapters", "profiles"])
        return Author, Book, Chapter, Profile

    async def _setup_user_post_comment_async(self, scenario_name):
        if not self._async_user_post_comment_setup:
            _, config = get_scenario(scenario_name)
            backend = self._configure_async_model_without_connection(AsyncUser, config)
            self._configure_async_model_without_connection(AsyncPost, config, backend)
            self._configure_async_model_without_connection(AsyncComment, config, backend)
            self._active_async_backends.append(backend)
            await backend.connect()
            try:
                await backend.introspect_and_adapt()
            except Exception:
                pass
            await self._execute_script_async(backend, USER_POST_COMMENT_SCHEMA)
            self._async_user_post_comment_setup = True
            self._created_tables.update(["users", "posts", "comments"])

    async def _setup_relation_boundary_async(self, scenario_name):
        if not self._async_relation_boundary_setup:
            _, config = get_scenario(scenario_name)
            backend = self._configure_async_model_without_connection(AsyncBoundaryOwner, config)
            self._configure_async_model_without_connection(AsyncBoundaryProfile, config, backend)
            self._configure_async_model_without_connection(AsyncBoundaryPost, config, backend)
            self._active_async_backends.append(backend)
            await backend.connect()
            try:
                await backend.introspect_and_adapt()
            except Exception:
                pass
            await self._execute_script_async(backend, RELATION_BOUNDARY_SCHEMA)
            self._created_tables.update(
                ["relation_boundary_owners", "relation_boundary_profiles", "relation_boundary_posts"]
            )
            self._async_relation_boundary_setup = True

    # -- IRelationAsyncProvider interface -------------------------------

    async def setup_employee_department_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[ActiveRecord], Type[ActiveRecord]]:
        return await self._setup_employee_department_async(scenario_name)

    async def setup_author_book_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[ActiveRecord], Type[ActiveRecord], Type[ActiveRecord], Type[ActiveRecord]]:
        return await self._setup_author_book_async(scenario_name)

    async def setup_user_model(self, scenario_name: str) -> Type[ActiveRecord]:
        await self._setup_user_post_comment_async(scenario_name)
        return AsyncUser

    async def setup_post_model(self, scenario_name: str) -> Type[ActiveRecord]:
        await self._setup_user_post_comment_async(scenario_name)
        return AsyncPost

    async def setup_comment_model(self, scenario_name: str) -> Type[ActiveRecord]:
        await self._setup_user_post_comment_async(scenario_name)
        return AsyncComment

    async def setup_relation_boundary_fixtures(
        self, scenario_name: str
    ) -> Tuple[Type[AsyncActiveRecord], Type[AsyncActiveRecord], Type[AsyncActiveRecord]]:
        await self._setup_relation_boundary_async(scenario_name)
        return AsyncBoundaryOwner, AsyncBoundaryProfile, AsyncBoundaryPost

    async def load_relation_boundary_dataset(
        self, scenario_name: str, dataset_name: str
    ) -> Dict[str, int]:
        await self._setup_relation_boundary_async(scenario_name)
        return await self._load_async_relation_boundary_dataset(dataset_name)

    async def _load_async_relation_boundary_dataset(self, dataset_name: str) -> Dict[str, int]:
        if dataset_name == "null_foreign_key":
            profile = AsyncBoundaryProfile(bio="No owner", owner_id=None)
            await profile.save()
            return {"profile_id": profile.id}

        if dataset_name == "orphan_foreign_key":
            missing_owner_id = 999999
            post = AsyncBoundaryPost(title="Orphan post", owner_id=missing_owner_id)
            await post.save()
            return {"post_id": post.id, "missing_owner_id": missing_owner_id}

        if dataset_name == "owner_without_children":
            owner = AsyncBoundaryOwner(name="Owner without children")
            await owner.save()
            return {"owner_id": owner.id}

        if dataset_name == "multiple_has_one_matches":
            owner = AsyncBoundaryOwner(name="Owner with duplicate profiles")
            await owner.save()
            first = AsyncBoundaryProfile(bio="First profile", owner_id=owner.id)
            await first.save()
            second = AsyncBoundaryProfile(bio="Second profile", owner_id=owner.id)
            await second.save()
            return {
                "owner_id": owner.id,
                "first_profile_id": first.id,
                "second_profile_id": second.id,
            }

        raise ValueError(f"Unknown relation boundary dataset: {dataset_name}")

    def _reset_async_setup_state(self):
        self._async_user_post_comment_setup = False
        self._async_relation_boundary_setup = False

    async def cleanup_after_test(self, scenario_name: str):
        for backend in self._active_async_backends:
            try:
                try:
                    if self._created_tables:
                        for table in list(self._created_tables):
                            try:
                                await backend.execute(
                                    f"BEGIN EXECUTE IMMEDIATE 'DROP TABLE {table} CASCADE CONSTRAINTS PURGE'; "
                                    f"EXCEPTION WHEN OTHERS THEN NULL; END;",
                                    options=self._ddl_options(),
                                )
                            except Exception:
                                pass
                except Exception:
                    pass
            finally:
                try:
                    await backend.disconnect()
                except Exception:
                    pass
        self._active_async_backends.clear()
        self._created_tables.clear()
        self._reset_async_setup_state()
